import type { FacetComposition } from "@facet/core";
import { CHART_TABLE_VIEW_COMPOSITION } from "./composition-chart-table.js";

/**
 * Default compositions are prompt-safe, node-free data assets: reusable stage
 * fragments with bounded metadata so an agent can choose useful patterns before
 * falling back to raw bricks.
 */
export const DEFAULT_COMPOSITIONS: readonly FacetComposition[] = [
  {
    name: "hero",
    description: "A compact product hero with a title, subtitle, and CTA.",
    metadata: {
      category: "marketing",
      useWhen: "Introducing a product, feature, or first screen.",
      avoidWhen: "The user needs dense operational data first.",
      tags: ["hero", "landing", "cta"],
      variants: ["default"],
      repeatable: false,
      preferredParent: "root",
    },
    slots: {
      title: "Your headline",
      subtitle: "A short supporting line.",
      cta: "Get started",
    },
    root: "hero.root",
    nodes: {
      "hero.root": {
        id: "hero.root",
        type: "section",
        title: "{{title}}",
        body: "{{subtitle}}",
        variant: "surface",
        children: ["hero.cta"],
      },
      "hero.cta": {
        id: "hero.cta",
        type: "button",
        label: "{{cta}}",
        variant: "primary",
        tone: "accent",
        onPress: { kind: "agent", name: "start" },
      },
    },
  },
  {
    name: "card",
    description: "A titled content card with body copy.",
    metadata: {
      category: "content",
      useWhen: "Grouping one concept, record, or explanation.",
      avoidWhen: "The content is a whole screen section.",
      tags: ["card", "content"],
      variants: ["default", "interactive"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: {
      title: "Card title",
      body: "Card body copy.",
    },
    root: "card.root",
    nodes: {
      "card.root": {
        id: "card.root",
        type: "card",
        title: "{{title}}",
        body: "{{body}}",
        variant: "default",
        children: [],
      },
    },
  },
  {
    name: "cta-button",
    description: "A single accent call-to-action button that fires an agent action.",
    metadata: {
      category: "action",
      useWhen: "The user should take one clear next action.",
      avoidWhen: "The action needs surrounding explanation or fields.",
      tags: ["button", "cta", "action"],
      variants: ["primary"],
      repeatable: true,
      preferredParent: "card",
    },
    slots: {
      label: "Get started",
    },
    root: "cta-button.root",
    nodes: {
      "cta-button.root": {
        id: "cta-button.root",
        type: "button",
        label: "{{label}}",
        variant: "primary",
        tone: "accent",
        onPress: { kind: "agent", name: "start" },
      },
    },
  },
  {
    name: "pricing-section",
    description: "A compact pricing comparison section with three plan cards.",
    metadata: {
      category: "commerce",
      useWhen: "Showing plans, packages, or tier comparison.",
      avoidWhen: "The user asked for a single plan detail.",
      tags: ["pricing", "plans", "commerce"],
      variants: ["three-card"],
      repeatable: false,
      preferredParent: "root",
    },
    slots: {
      title: "Choose a plan",
      starter: "Starter",
      pro: "Pro",
      enterprise: "Enterprise",
      cta: "Compare plans",
    },
    root: "pricing-section.root",
    nodes: {
      "pricing-section.root": {
        id: "pricing-section.root",
        type: "section",
        title: "{{title}}",
        variant: "surface",
        children: ["pricing-section.starter", "pricing-section.pro", "pricing-section.enterprise"],
      },
      "pricing-section.starter": {
        id: "pricing-section.starter",
        type: "card",
        title: "{{starter}}",
        body: "Simple tools for early teams.",
        children: ["pricing-section.starter-price"],
      },
      "pricing-section.starter-price": {
        id: "pricing-section.starter-price",
        type: "metric",
        label: "Monthly",
        value: "$19",
      },
      "pricing-section.pro": {
        id: "pricing-section.pro",
        type: "card",
        title: "{{pro}}",
        body: "Advanced workflows and analytics.",
        tone: "accent",
        children: ["pricing-section.pro-price", "pricing-section.cta"],
      },
      "pricing-section.pro-price": {
        id: "pricing-section.pro-price",
        type: "metric",
        label: "Monthly",
        value: "$49",
      },
      "pricing-section.cta": {
        id: "pricing-section.cta",
        type: "button",
        label: "{{cta}}",
        variant: "primary",
        onPress: { kind: "agent", name: "compare_pricing" },
      },
      "pricing-section.enterprise": {
        id: "pricing-section.enterprise",
        type: "card",
        title: "{{enterprise}}",
        body: "Custom controls for larger organizations.",
        children: ["pricing-section.enterprise-badge"],
      },
      "pricing-section.enterprise-badge": {
        use: "badge",
        slots: { label: "Custom" },
      },
    },
  },
  {
    name: "faq-section",
    description: "A concise FAQ list for common questions.",
    metadata: {
      category: "support",
      useWhen: "Answering several predictable questions.",
      avoidWhen: "The user needs an interactive troubleshooting flow.",
      tags: ["faq", "support", "list"],
      variants: ["compact"],
      repeatable: false,
      preferredParent: "root",
    },
    slots: {
      title: "Questions",
      q1: "What is included?",
      q2: "Can I cancel?",
      q3: "How do I get support?",
    },
    root: "faq-section.root",
    nodes: {
      "faq-section.root": {
        id: "faq-section.root",
        type: "section",
        title: "{{title}}",
        children: ["faq-section.list"],
      },
      "faq-section.list": {
        id: "faq-section.list",
        type: "list",
        items: [{ title: "{{q1}}" }, { title: "{{q2}}" }, { title: "{{q3}}" }],
      },
    },
  },
  {
    name: "dashboard-summary",
    description: "A KPI summary section with stats and status.",
    metadata: {
      category: "dashboard",
      useWhen: "Summarizing current performance or account state.",
      avoidWhen: "The user asked for detailed raw records first.",
      tags: ["dashboard", "metrics", "summary"],
      variants: ["kpi"],
      repeatable: false,
      preferredParent: "root",
    },
    slots: {
      title: "Overview",
      metric: "Revenue",
      value: "$42k",
      delta: "+12%",
    },
    root: "dashboard-summary.root",
    nodes: {
      "dashboard-summary.root": {
        id: "dashboard-summary.root",
        type: "section",
        title: "{{title}}",
        variant: "surface",
        children: [
          "dashboard-summary.stat",
          "dashboard-summary.badge",
          "dashboard-summary.progress",
        ],
      },
      "dashboard-summary.stat": {
        id: "dashboard-summary.stat",
        type: "stat",
        label: "{{metric}}",
        value: "{{value}}",
        delta: "{{delta}}",
        tone: "success",
      },
      "dashboard-summary.badge": {
        use: "badge-success",
        slots: { label: "Healthy" },
      },
      "dashboard-summary.progress": {
        id: "dashboard-summary.progress",
        type: "progress",
        label: "Goal",
        value: 72,
        tone: "accent",
      },
    },
  },
  {
    name: "settings-panel",
    description: "A settings card with two editable fields and a save action.",
    metadata: {
      category: "settings",
      useWhen: "Collecting a small configuration update.",
      avoidWhen: "The form needs many fields or validation steps.",
      tags: ["settings", "form", "fields"],
      variants: ["compact"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: {
      title: "Settings",
      email: "Email",
      timezone: "Timezone",
      save: "Save",
    },
    root: "settings-panel.root",
    nodes: {
      "settings-panel.root": {
        id: "settings-panel.root",
        type: "card",
        title: "{{title}}",
        children: ["settings-panel.email", "settings-panel.timezone", "settings-panel.save"],
      },
      "settings-panel.email": {
        id: "settings-panel.email",
        type: "input",
        name: "email",
        input: "email",
        label: "{{email}}",
        style: { width: "full" },
      },
      "settings-panel.timezone": {
        id: "settings-panel.timezone",
        type: "input",
        name: "timezone",
        input: "select",
        label: "{{timezone}}",
        options: ["UTC", "PST", "EST"],
        style: { width: "full" },
      },
      "settings-panel.save": {
        id: "settings-panel.save",
        type: "button",
        label: "{{save}}",
        variant: "primary",
        onPress: { kind: "agent", name: "save_settings", collect: "settings-panel.root" },
      },
    },
  },
  {
    name: "feature-grid",
    description: "A three-card feature grid.",
    metadata: {
      category: "marketing",
      useWhen: "Explaining a small set of product capabilities.",
      avoidWhen: "The user needs one focused workflow.",
      tags: ["features", "grid", "cards"],
      variants: ["three-card"],
      repeatable: false,
      preferredParent: "root",
    },
    slots: {
      title: "Features",
      first: "Fast setup",
      second: "Live UI",
      third: "Safe patches",
    },
    root: "feature-grid.root",
    nodes: {
      "feature-grid.root": {
        id: "feature-grid.root",
        type: "section",
        title: "{{title}}",
        children: ["feature-grid.first", "feature-grid.second", "feature-grid.third"],
      },
      "feature-grid.first": {
        id: "feature-grid.first",
        type: "card",
        title: "{{first}}",
        body: "Start from safe default UI patterns.",
        children: [],
      },
      "feature-grid.second": {
        id: "feature-grid.second",
        type: "card",
        title: "{{second}}",
        body: "Render task-specific screens as the conversation changes.",
        children: [],
      },
      "feature-grid.third": {
        id: "feature-grid.third",
        type: "card",
        title: "{{third}}",
        body: "Keep every update declarative and bounded.",
        children: [],
      },
    },
  },
  {
    name: "empty-state",
    description: "A compact empty state with a recovery action.",
    metadata: {
      category: "feedback",
      useWhen: "There is no data yet and the user needs a clear next action.",
      avoidWhen: "There is meaningful content to summarize.",
      tags: ["empty", "feedback", "action"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: {
      title: "Nothing here yet",
      body: "Create the first item to get started.",
      action: "Create item",
    },
    root: "empty-state.root",
    nodes: {
      "empty-state.root": {
        id: "empty-state.root",
        type: "card",
        title: "{{title}}",
        body: "{{body}}",
        children: ["empty-state.action"],
      },
      "empty-state.action": {
        id: "empty-state.action",
        type: "button",
        label: "{{action}}",
        variant: "primary",
        onPress: { kind: "agent", name: "create_item" },
      },
    },
  },
  {
    name: "support-triage",
    description: "A support triage card with issue type selection.",
    metadata: {
      category: "support",
      useWhen: "Collecting basic support context before agent follow-up.",
      avoidWhen: "The user already gave all required details.",
      tags: ["support", "triage", "form"],
      variants: ["compact"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: {
      title: "How can we help?",
      issue: "Issue type",
      details: "Details",
      submit: "Send",
    },
    root: "support-triage.root",
    nodes: {
      "support-triage.root": {
        id: "support-triage.root",
        type: "card",
        title: "{{title}}",
        children: ["support-triage.issue", "support-triage.details", "support-triage.submit"],
      },
      "support-triage.issue": {
        id: "support-triage.issue",
        type: "input",
        name: "issue_type",
        input: "select",
        label: "{{issue}}",
        options: ["Billing", "Technical", "Account"],
        style: { width: "full" },
      },
      "support-triage.details": {
        id: "support-triage.details",
        type: "input",
        name: "details",
        input: "text",
        label: "{{details}}",
        style: { width: "full" },
      },
      "support-triage.submit": {
        id: "support-triage.submit",
        type: "button",
        label: "{{submit}}",
        variant: "primary",
        onPress: { kind: "agent", name: "submit_support", collect: "support-triage.root" },
      },
    },
  },
  // --- Per-tone badge compositions (PR-5a: badge demoted to composition) ------
  // Each bakes the fully-resolved tokens the removed `badge` component rendered
  // for its tone: rendererDefault(tone) ∪ theme recipe.box/text ∪ recipe.parts.
  // The base `badge` reproduces the tone-less/`info` render (empty recipe →
  // renderer defaults only); the tone-named variants fold in their recipe.
  {
    name: "badge",
    description: "A compact neutral status chip.",
    metadata: {
      category: "feedback",
      useWhen: "Labeling a compact status, tag, or count.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "chip"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "card",
    },
    slots: { label: "Status" },
    root: "badge.root",
    nodes: {
      "badge.root": {
        id: "badge.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["badge.label"],
      },
      "badge.label": {
        id: "badge.label",
        type: "text",
        value: "{{label}}",
        style: { color: "fg", size: "sm", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-neutral",
    description: "A compact neutral-toned status chip.",
    metadata: {
      category: "feedback",
      useWhen: "Labeling a compact neutral status or tag.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "neutral"],
      variants: ["neutral"],
      repeatable: true,
      preferredParent: "card",
    },
    slots: { label: "Status" },
    root: "badge-neutral.root",
    nodes: {
      "badge-neutral.root": {
        id: "badge-neutral.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["badge-neutral.label"],
      },
      "badge-neutral.label": {
        id: "badge-neutral.label",
        type: "text",
        value: "{{label}}",
        style: { color: "neutral", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-success",
    description: "A compact success-toned status chip.",
    metadata: {
      category: "feedback",
      useWhen: "Labeling a healthy, complete, or positive status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "success"],
      variants: ["success"],
      repeatable: true,
      preferredParent: "card",
    },
    slots: { label: "Healthy" },
    root: "badge-success.root",
    nodes: {
      "badge-success.root": {
        id: "badge-success.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-success.label"],
      },
      "badge-success.label": {
        id: "badge-success.label",
        type: "text",
        value: "{{label}}",
        style: { color: "success", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-warning",
    description: "A compact warning-toned status chip.",
    metadata: {
      category: "feedback",
      useWhen: "Labeling a caution, pending, or attention status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "warning"],
      variants: ["warning"],
      repeatable: true,
      preferredParent: "card",
    },
    slots: { label: "Pending" },
    root: "badge-warning.root",
    nodes: {
      "badge-warning.root": {
        id: "badge-warning.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-warning.label"],
      },
      "badge-warning.label": {
        id: "badge-warning.label",
        type: "text",
        value: "{{label}}",
        style: { color: "warning", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-danger",
    description: "A compact danger-toned status chip.",
    metadata: {
      category: "feedback",
      useWhen: "Labeling a failing, blocked, or critical status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "danger"],
      variants: ["danger"],
      repeatable: true,
      preferredParent: "card",
    },
    slots: { label: "Failed" },
    root: "badge-danger.root",
    nodes: {
      "badge-danger.root": {
        id: "badge-danger.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-danger.label"],
      },
      "badge-danger.label": {
        id: "badge-danger.label",
        type: "text",
        value: "{{label}}",
        style: { color: "danger", size: "xs", weight: "semibold" },
      },
    },
  },
  // --- Per-tone alert compositions (PR-5a: alert demoted to composition) -------
  // box baked from rendererDefault ∪ recipe.box; title/body texts baked from the
  // title/body defaults ∪ recipe.text ∪ recipe.parts. Base `alert` reproduces the
  // tone-less render (empty recipe → renderer defaults only, body has no tokens).
  {
    name: "alert",
    description: "A neutral notice panel with a title and body.",
    metadata: {
      category: "feedback",
      useWhen: "Calling out a plain notice or message.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "feedback"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: { title: "Notice", body: "Something you should know." },
    root: "alert.root",
    nodes: {
      "alert.root": {
        id: "alert.root",
        type: "box",
        style: { gap: "xs", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert.title", "alert.body"],
      },
      "alert.title": {
        id: "alert.title",
        type: "text",
        value: "{{title}}",
        style: { weight: "bold" },
      },
      "alert.body": {
        id: "alert.body",
        type: "text",
        value: "{{body}}",
      },
    },
  },
  {
    name: "alert-info",
    description: "An informational notice panel with a title and body.",
    metadata: {
      category: "feedback",
      useWhen: "Sharing informational context or a tip.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "info"],
      variants: ["info"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: { title: "Heads up", body: "Here is something useful to know." },
    root: "alert-info.root",
    nodes: {
      "alert-info.root": {
        id: "alert-info.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-info.title", "alert-info.body"],
      },
      "alert-info.title": {
        id: "alert-info.title",
        type: "text",
        value: "{{title}}",
        style: { weight: "bold", color: "info" },
      },
      "alert-info.body": {
        id: "alert-info.body",
        type: "text",
        value: "{{body}}",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-success",
    description: "A success notice panel with a title and body.",
    metadata: {
      category: "feedback",
      useWhen: "Confirming a completed or successful action.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "success"],
      variants: ["success"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: { title: "Success", body: "Your changes were saved." },
    root: "alert-success.root",
    nodes: {
      "alert-success.root": {
        id: "alert-success.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-success.title", "alert-success.body"],
      },
      "alert-success.title": {
        id: "alert-success.title",
        type: "text",
        value: "{{title}}",
        style: { weight: "bold", color: "success" },
      },
      "alert-success.body": {
        id: "alert-success.body",
        type: "text",
        value: "{{body}}",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-warning",
    description: "A warning notice panel with a title and body.",
    metadata: {
      category: "feedback",
      useWhen: "Warning about a caution or pending condition.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "warning"],
      variants: ["warning"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: { title: "Warning", body: "Please review before continuing." },
    root: "alert-warning.root",
    nodes: {
      "alert-warning.root": {
        id: "alert-warning.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-warning.title", "alert-warning.body"],
      },
      "alert-warning.title": {
        id: "alert-warning.title",
        type: "text",
        value: "{{title}}",
        style: { weight: "bold", color: "warning" },
      },
      "alert-warning.body": {
        id: "alert-warning.body",
        type: "text",
        value: "{{body}}",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-danger",
    description: "A danger notice panel with a title and body.",
    metadata: {
      category: "feedback",
      useWhen: "Flagging an error or critical condition.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "danger"],
      variants: ["danger"],
      repeatable: true,
      preferredParent: "section",
    },
    slots: { title: "Error", body: "Something went wrong." },
    root: "alert-danger.root",
    nodes: {
      "alert-danger.root": {
        id: "alert-danger.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-danger.title", "alert-danger.body"],
      },
      "alert-danger.title": {
        id: "alert-danger.title",
        type: "text",
        value: "{{title}}",
        style: { weight: "bold", color: "danger" },
      },
      "alert-danger.body": {
        id: "alert-danger.body",
        type: "text",
        value: "{{body}}",
        style: { color: "fg" },
      },
    },
  },
  CHART_TABLE_VIEW_COMPOSITION,
];
