import type { FacetComposition } from "@facet/core";
import { CHART_TABLE_VIEW_COMPOSITION } from "./composition-chart-table.js";

/**
 * Default compositions are data-only, self-contained native reference
 * datasets. An agent may inspect one as an example, then author ordinary stage
 * nodes with the existing native tools; these assets are not templates or
 * renderer extensions.
 */
export const DEFAULT_COMPOSITIONS: readonly FacetComposition[] = [
  {
    name: "hero",
    metadata: {
      description: "A compact product hero with a title, subtitle, and CTA.",
      category: "marketing",
      useWhen: "Introducing a product, feature, or first screen.",
      avoidWhen: "The user needs dense operational data first.",
      tags: ["hero", "landing", "cta"],
      variants: ["default"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "hero.root",
    nodes: {
      "hero.root": {
        id: "hero.root",
        type: "section",
        title: "Ship polished interfaces in minutes",
        body: "Compose safe, live UI for each user without shipping a new frontend.",
        variant: "surface",
        children: ["hero.cta"],
      },
      "hero.cta": {
        id: "hero.cta",
        type: "button",
        label: "Get started",
        variant: "primary",
        tone: "accent",
        onPress: { kind: "agent", name: "start" },
      },
    },
  },
  {
    name: "card",
    metadata: {
      description: "A titled content card with body copy.",
      category: "content",
      useWhen: "Grouping one concept, record, or explanation.",
      avoidWhen: "The content is a whole screen section.",
      tags: ["card", "content"],
      variants: ["default", "interactive"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "card.root",
    nodes: {
      "card.root": {
        id: "card.root",
        type: "card",
        title: "Quarterly planning",
        body: "Review goals, owners, and open decisions for the next release.",
        variant: "default",
        children: [],
      },
    },
  },
  {
    name: "cta-button",
    metadata: {
      description: "A single accent call-to-action button that fires an agent action.",
      category: "action",
      useWhen: "The user should take one clear next action.",
      avoidWhen: "The action needs surrounding explanation or fields.",
      tags: ["button", "cta", "action"],
      variants: ["primary"],
      repeatable: true,
      preferredParent: "card",
    },
    root: "cta-button.root",
    nodes: {
      "cta-button.root": {
        id: "cta-button.root",
        type: "button",
        label: "Get started",
        variant: "primary",
        tone: "accent",
        onPress: { kind: "agent", name: "start" },
      },
    },
  },
  {
    name: "pricing-section",
    metadata: {
      description: "A compact pricing comparison section with three plan cards.",
      category: "commerce",
      useWhen: "Showing plans, packages, or tier comparison.",
      avoidWhen: "The user asked for a single plan detail.",
      tags: ["pricing", "plans", "commerce"],
      variants: ["three-card"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "pricing-section.root",
    nodes: {
      "pricing-section.root": {
        id: "pricing-section.root",
        type: "section",
        title: "Choose a plan",
        variant: "surface",
        children: ["pricing-section.starter", "pricing-section.pro", "pricing-section.enterprise"],
      },
      "pricing-section.starter": {
        id: "pricing-section.starter",
        type: "card",
        title: "Starter",
        body: "Simple tools for early teams.",
        children: ["pricing-section.starter-price"],
      },
      "pricing-section.starter-price": {
        id: "pricing-section.starter-price",
        type: "metric",
        label: "Monthly",
        value: "$19",
      },
      "pricing-section.pro": {
        id: "pricing-section.pro",
        type: "card",
        title: "Pro",
        body: "Advanced workflows and analytics.",
        tone: "accent",
        children: ["pricing-section.pro-price", "pricing-section.cta"],
      },
      "pricing-section.pro-price": {
        id: "pricing-section.pro-price",
        type: "metric",
        label: "Monthly",
        value: "$49",
      },
      "pricing-section.cta": {
        id: "pricing-section.cta",
        type: "button",
        label: "Compare plans",
        variant: "primary",
        onPress: { kind: "agent", name: "compare_pricing" },
      },
      "pricing-section.enterprise": {
        id: "pricing-section.enterprise",
        type: "card",
        title: "Enterprise",
        body: "Custom controls for larger organizations.",
        children: ["pricing-section.enterprise-badge"],
      },
      "pricing-section.enterprise-badge": {
        id: "pricing-section.enterprise-badge",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["pricing-section.enterprise-badge-label"],
      },
      "pricing-section.enterprise-badge-label": {
        id: "pricing-section.enterprise-badge-label",
        type: "text",
        value: "Custom",
        style: { color: "fg", size: "sm", weight: "semibold" },
      },
    },
  },
  {
    name: "faq-section",
    metadata: {
      description: "A concise FAQ list for common questions.",
      category: "support",
      useWhen: "Answering several predictable questions.",
      avoidWhen: "The user needs an interactive troubleshooting flow.",
      tags: ["faq", "support", "list"],
      variants: ["compact"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "faq-section.root",
    nodes: {
      "faq-section.root": {
        id: "faq-section.root",
        type: "section",
        title: "Questions",
        children: ["faq-section.list"],
      },
      "faq-section.list": {
        id: "faq-section.list",
        type: "list",
        items: [
          { title: "What is included?" },
          { title: "Can I cancel?" },
          { title: "How do I get support?" },
        ],
      },
    },
  },
  {
    name: "dashboard-summary",
    metadata: {
      description: "A KPI summary section with stats and status.",
      category: "dashboard",
      useWhen: "Summarizing current performance or account state.",
      avoidWhen: "The user asked for detailed raw records first.",
      tags: ["dashboard", "metrics", "summary"],
      variants: ["kpi"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "dashboard-summary.root",
    nodes: {
      "dashboard-summary.root": {
        id: "dashboard-summary.root",
        type: "section",
        title: "Overview",
        variant: "surface",
        children: [
          "dashboard-summary.stat",
          "dashboard-summary.badge",
          "dashboard-summary.progress",
        ],
      },
      "dashboard-summary.stat": {
        id: "dashboard-summary.stat",
        type: "stat",
        label: "Revenue",
        value: "$42k",
        delta: "+12%",
        tone: "success",
      },
      "dashboard-summary.badge": {
        id: "dashboard-summary.badge",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["dashboard-summary.badge-label"],
      },
      "dashboard-summary.badge-label": {
        id: "dashboard-summary.badge-label",
        type: "text",
        value: "Healthy",
        style: { color: "success", size: "xs", weight: "semibold" },
      },
      "dashboard-summary.progress": {
        id: "dashboard-summary.progress",
        type: "progress",
        label: "Goal",
        value: 72,
        tone: "accent",
      },
    },
  },
  {
    name: "settings-panel",
    metadata: {
      description: "A settings card with two editable fields and a save action.",
      category: "settings",
      useWhen: "Collecting a small configuration update.",
      avoidWhen: "The form needs many fields or validation steps.",
      tags: ["settings", "form", "fields"],
      variants: ["compact"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "settings-panel.root",
    nodes: {
      "settings-panel.root": {
        id: "settings-panel.root",
        type: "card",
        title: "Workspace settings",
        children: ["settings-panel.email", "settings-panel.timezone", "settings-panel.save"],
      },
      "settings-panel.email": {
        id: "settings-panel.email",
        type: "input",
        name: "email",
        input: "email",
        label: "Notification email",
        style: { width: "full" },
      },
      "settings-panel.timezone": {
        id: "settings-panel.timezone",
        type: "input",
        name: "timezone",
        input: "select",
        label: "Timezone",
        options: ["UTC", "PST", "EST"],
        style: { width: "full" },
      },
      "settings-panel.save": {
        id: "settings-panel.save",
        type: "button",
        label: "Save settings",
        variant: "primary",
        onPress: { kind: "agent", name: "save_settings", collect: "settings-panel.root" },
      },
    },
  },
  {
    name: "feature-grid",
    metadata: {
      description: "A three-card feature grid.",
      category: "marketing",
      useWhen: "Explaining a small set of product capabilities.",
      avoidWhen: "The user needs one focused workflow.",
      tags: ["features", "grid", "cards"],
      variants: ["three-card"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "feature-grid.root",
    nodes: {
      "feature-grid.root": {
        id: "feature-grid.root",
        type: "section",
        title: "Features",
        children: ["feature-grid.first", "feature-grid.second", "feature-grid.third"],
      },
      "feature-grid.first": {
        id: "feature-grid.first",
        type: "card",
        title: "Fast setup",
        body: "Start from safe default UI patterns.",
        children: [],
      },
      "feature-grid.second": {
        id: "feature-grid.second",
        type: "card",
        title: "Live UI",
        body: "Render task-specific screens as the conversation changes.",
        children: [],
      },
      "feature-grid.third": {
        id: "feature-grid.third",
        type: "card",
        title: "Safe patches",
        body: "Keep every update declarative and bounded.",
        children: [],
      },
    },
  },
  {
    name: "empty-state",
    metadata: {
      description: "A compact empty state with a recovery action.",
      category: "feedback",
      useWhen: "There is no data yet and the user needs a clear next action.",
      avoidWhen: "There is meaningful content to summarize.",
      tags: ["empty", "feedback", "action"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "empty-state.root",
    nodes: {
      "empty-state.root": {
        id: "empty-state.root",
        type: "card",
        title: "No projects yet",
        body: "Create your first project to start organizing this workspace.",
        children: ["empty-state.action"],
      },
      "empty-state.action": {
        id: "empty-state.action",
        type: "button",
        label: "Create project",
        variant: "primary",
        onPress: { kind: "agent", name: "create_item" },
      },
    },
  },
  {
    name: "support-triage",
    metadata: {
      description: "A support triage card with issue type selection.",
      category: "support",
      useWhen: "Collecting basic support context before agent follow-up.",
      avoidWhen: "The user already gave all required details.",
      tags: ["support", "triage", "form"],
      variants: ["compact"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "support-triage.root",
    nodes: {
      "support-triage.root": {
        id: "support-triage.root",
        type: "card",
        title: "How can we help?",
        children: ["support-triage.issue", "support-triage.details", "support-triage.submit"],
      },
      "support-triage.issue": {
        id: "support-triage.issue",
        type: "input",
        name: "issue_type",
        input: "select",
        label: "Issue type",
        options: ["Billing", "Technical", "Account"],
        style: { width: "full" },
      },
      "support-triage.details": {
        id: "support-triage.details",
        type: "input",
        name: "details",
        input: "text",
        label: "Describe what happened",
        style: { width: "full" },
      },
      "support-triage.submit": {
        id: "support-triage.submit",
        type: "button",
        label: "Send request",
        variant: "primary",
        onPress: { kind: "agent", name: "submit_support", collect: "support-triage.root" },
      },
    },
  },
  // --- Per-tone badge compositions (PR-5a: badge demoted to composition) ------
  // Each bakes the fully-resolved tokens the removed `badge` component rendered
  // for its tone: rendererDefault(tone) ∪ theme recipe.box/text ∪ recipe.parts.
  // The base `badge` reproduces the tone-less/`info` render (empty recipe →
  // renderer defaults only); the tone-named variants fold in their recipe.
  {
    name: "badge",
    metadata: {
      description: "A compact neutral status chip.",
      category: "feedback",
      useWhen: "Labeling a compact status, tag, or count.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "chip"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "card",
    },
    root: "badge.root",
    nodes: {
      "badge.root": {
        id: "badge.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["badge.label"],
      },
      "badge.label": {
        id: "badge.label",
        type: "text",
        value: "In review",
        style: { color: "fg", size: "sm", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-neutral",
    metadata: {
      description: "A compact neutral-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a compact neutral status or tag.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "neutral"],
      variants: ["neutral"],
      repeatable: true,
      preferredParent: "card",
    },
    root: "badge-neutral.root",
    nodes: {
      "badge-neutral.root": {
        id: "badge-neutral.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["badge-neutral.label"],
      },
      "badge-neutral.label": {
        id: "badge-neutral.label",
        type: "text",
        value: "Draft",
        style: { color: "neutral", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-success",
    metadata: {
      description: "A compact success-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a healthy, complete, or positive status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "success"],
      variants: ["success"],
      repeatable: true,
      preferredParent: "card",
    },
    root: "badge-success.root",
    nodes: {
      "badge-success.root": {
        id: "badge-success.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-success.label"],
      },
      "badge-success.label": {
        id: "badge-success.label",
        type: "text",
        value: "Healthy",
        style: { color: "success", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-warning",
    metadata: {
      description: "A compact warning-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a caution, pending, or attention status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "warning"],
      variants: ["warning"],
      repeatable: true,
      preferredParent: "card",
    },
    root: "badge-warning.root",
    nodes: {
      "badge-warning.root": {
        id: "badge-warning.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-warning.label"],
      },
      "badge-warning.label": {
        id: "badge-warning.label",
        type: "text",
        value: "Pending",
        style: { color: "warning", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-danger",
    metadata: {
      description: "A compact danger-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a failing, blocked, or critical status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "danger"],
      variants: ["danger"],
      repeatable: true,
      preferredParent: "card",
    },
    root: "badge-danger.root",
    nodes: {
      "badge-danger.root": {
        id: "badge-danger.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-danger.label"],
      },
      "badge-danger.label": {
        id: "badge-danger.label",
        type: "text",
        value: "Failed",
        style: { color: "danger", size: "xs", weight: "semibold" },
      },
    },
  },
  // --- Per-tone alert compositions (PR-5a: alert demoted to composition) -------
  // box baked from rendererDefault ∪ recipe.box; title/body texts baked from the
  // title/body defaults ∪ recipe.text ∪ recipe.parts. Base `alert` reproduces the
  // tone-less render (empty recipe → renderer defaults only, body has no tokens).
  {
    name: "alert",
    metadata: {
      description: "A neutral notice panel with a title and body.",
      category: "feedback",
      useWhen: "Calling out a plain notice or message.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "feedback"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "alert.root",
    nodes: {
      "alert.root": {
        id: "alert.root",
        type: "box",
        style: { gap: "xs", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert.title", "alert.body"],
      },
      "alert.title": {
        id: "alert.title",
        type: "text",
        value: "Scheduled maintenance",
        style: { weight: "bold" },
      },
      "alert.body": {
        id: "alert.body",
        type: "text",
        value: "The dashboard will be read-only for ten minutes tonight.",
        style: {},
      },
    },
  },
  {
    name: "alert-info",
    metadata: {
      description: "An informational notice panel with a title and body.",
      category: "feedback",
      useWhen: "Sharing informational context or a tip.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "info"],
      variants: ["info"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "alert-info.root",
    nodes: {
      "alert-info.root": {
        id: "alert-info.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-info.title", "alert-info.body"],
      },
      "alert-info.title": {
        id: "alert-info.title",
        type: "text",
        value: "New export format",
        style: { weight: "bold", color: "info" },
      },
      "alert-info.body": {
        id: "alert-info.body",
        type: "text",
        value: "CSV exports now include timezone-aware date and time values.",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-success",
    metadata: {
      description: "A success notice panel with a title and body.",
      category: "feedback",
      useWhen: "Confirming a completed or successful action.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "success"],
      variants: ["success"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "alert-success.root",
    nodes: {
      "alert-success.root": {
        id: "alert-success.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-success.title", "alert-success.body"],
      },
      "alert-success.title": {
        id: "alert-success.title",
        type: "text",
        value: "Changes saved",
        style: { weight: "bold", color: "success" },
      },
      "alert-success.body": {
        id: "alert-success.body",
        type: "text",
        value: "Your workspace settings are up to date.",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-warning",
    metadata: {
      description: "A warning notice panel with a title and body.",
      category: "feedback",
      useWhen: "Warning about a caution or pending condition.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "warning"],
      variants: ["warning"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "alert-warning.root",
    nodes: {
      "alert-warning.root": {
        id: "alert-warning.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-warning.title", "alert-warning.body"],
      },
      "alert-warning.title": {
        id: "alert-warning.title",
        type: "text",
        value: "Storage almost full",
        style: { weight: "bold", color: "warning" },
      },
      "alert-warning.body": {
        id: "alert-warning.body",
        type: "text",
        value: "Remove unused files before the next scheduled import.",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-danger",
    metadata: {
      description: "A danger notice panel with a title and body.",
      category: "feedback",
      useWhen: "Flagging an error or critical condition.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "danger"],
      variants: ["danger"],
      repeatable: true,
      preferredParent: "section",
    },
    root: "alert-danger.root",
    nodes: {
      "alert-danger.root": {
        id: "alert-danger.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-danger.title", "alert-danger.body"],
      },
      "alert-danger.title": {
        id: "alert-danger.title",
        type: "text",
        value: "Payment failed",
        style: { weight: "bold", color: "danger" },
      },
      "alert-danger.body": {
        id: "alert-danger.body",
        type: "text",
        value: "Update the billing method to keep the workspace active.",
        style: { color: "fg" },
      },
    },
  },
  CHART_TABLE_VIEW_COMPOSITION,
];
