import type { FacetComposition } from "@facet/core";
import { CHART_TABLE_VIEW_COMPOSITION } from "./composition-chart-table.js";
import {
  CARD_COMPOSITION,
  EMPTY_STATE_COMPOSITION,
  SECTION_COMPOSITION,
} from "./composition-containers.js";
import { CONTROL_COMPOSITIONS } from "./composition-controls.js";

/**
 * Default compositions are data-only, self-contained native reference
 * datasets. An agent may inspect one as an example, then author ordinary stage
 * nodes with the existing native tools; these assets are not templates or
 * renderer extensions.
 */
export const DEFAULT_COMPOSITIONS: readonly FacetComposition[] = [
  {
    name: "hero",
    metadata: {
      description: "A compact product hero with a title, subtitle, and CTA.",
      category: "marketing",
      useWhen: "Introducing a product, feature, or first screen.",
      avoidWhen: "The user needs dense operational data first.",
      tags: ["hero", "landing", "cta"],
      variants: ["default"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "hero.root",
    nodes: {
      "hero.root": {
        id: "hero.root",
        type: "box",
        style: { bg: "surface", gap: "md", pad: "lg", radius: "lg", width: "full" },
        children: ["hero.title", "hero.body", "hero.cta"],
      },
      "hero.title": {
        id: "hero.title",
        type: "text",
        value: "Ship polished interfaces in minutes",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "hero.body": {
        id: "hero.body",
        type: "text",
        value: "Compose safe, live UI for each user without shipping a new frontend.",
        style: { color: "fg" },
      },
      "hero.cta": {
        id: "hero.cta",
        type: "box",
        style: { bg: "accent", pad: "sm", radius: "md", shadow: "sm" },
        children: ["hero.cta-label"],
        onPress: { kind: "agent", name: "start" },
      },
      "hero.cta-label": {
        id: "hero.cta-label",
        type: "text",
        value: "Get started",
        style: { color: "accent-fg", align: "center", weight: "semibold" },
      },
    },
  },
  CARD_COMPOSITION,
  SECTION_COMPOSITION,
  ...CONTROL_COMPOSITIONS,
  {
    name: "pricing-section",
    metadata: {
      description: "A compact pricing comparison section with three plan cards.",
      category: "commerce",
      useWhen: "Showing plans, packages, or tier comparison.",
      avoidWhen: "The user asked for a single plan detail.",
      tags: ["pricing", "plans", "commerce"],
      variants: ["three-card"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "pricing-section.root",
    nodes: {
      "pricing-section.root": {
        id: "pricing-section.root",
        type: "box",
        style: { bg: "surface", gap: "md", pad: "lg", radius: "lg", width: "full" },
        children: [
          "pricing-section.title",
          "pricing-section.starter",
          "pricing-section.pro",
          "pricing-section.enterprise",
        ],
      },
      "pricing-section.title": {
        id: "pricing-section.title",
        type: "text",
        value: "Choose a plan",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "pricing-section.starter": {
        id: "pricing-section.starter",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: ["pricing-section.starter-header", "pricing-section.starter-price"],
      },
      "pricing-section.starter-header": {
        id: "pricing-section.starter-header",
        type: "box",
        style: { gap: "xs" },
        children: ["pricing-section.starter-title", "pricing-section.starter-body"],
      },
      "pricing-section.starter-title": {
        id: "pricing-section.starter-title",
        type: "text",
        value: "Starter",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "pricing-section.starter-body": {
        id: "pricing-section.starter-body",
        type: "text",
        value: "Simple tools for early teams.",
        style: { color: "fg-muted" },
      },
      "pricing-section.starter-price": {
        id: "pricing-section.starter-price",
        type: "box",
        style: { gap: "xs" },
        children: ["pricing-section.starter-price-label", "pricing-section.starter-price-value"],
      },
      "pricing-section.starter-price-label": {
        id: "pricing-section.starter-price-label",
        type: "text",
        value: "Monthly",
        style: { color: "fg-muted", size: "sm" },
      },
      "pricing-section.starter-price-value": {
        id: "pricing-section.starter-price-value",
        type: "text",
        value: "$19",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "pricing-section.pro": {
        id: "pricing-section.pro",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: [
          "pricing-section.pro-header",
          "pricing-section.pro-price",
          "pricing-section.cta",
        ],
      },
      "pricing-section.pro-header": {
        id: "pricing-section.pro-header",
        type: "box",
        style: { gap: "xs" },
        children: ["pricing-section.pro-title", "pricing-section.pro-body"],
      },
      "pricing-section.pro-title": {
        id: "pricing-section.pro-title",
        type: "text",
        value: "Pro",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "pricing-section.pro-body": {
        id: "pricing-section.pro-body",
        type: "text",
        value: "Advanced workflows and analytics.",
        style: { color: "fg-muted" },
      },
      "pricing-section.pro-price": {
        id: "pricing-section.pro-price",
        type: "box",
        style: { gap: "xs" },
        children: ["pricing-section.pro-price-label", "pricing-section.pro-price-value"],
      },
      "pricing-section.pro-price-label": {
        id: "pricing-section.pro-price-label",
        type: "text",
        value: "Monthly",
        style: { color: "fg-muted", size: "sm" },
      },
      "pricing-section.pro-price-value": {
        id: "pricing-section.pro-price-value",
        type: "text",
        value: "$49",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "pricing-section.cta": {
        id: "pricing-section.cta",
        type: "box",
        style: { bg: "accent", pad: "sm", radius: "md", shadow: "sm" },
        children: ["pricing-section.cta-label"],
        onPress: { kind: "agent", name: "compare_pricing" },
      },
      "pricing-section.cta-label": {
        id: "pricing-section.cta-label",
        type: "text",
        value: "Compare plans",
        style: { color: "accent-fg", align: "center", weight: "semibold" },
      },
      "pricing-section.enterprise": {
        id: "pricing-section.enterprise",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: ["pricing-section.enterprise-header", "pricing-section.enterprise-badge"],
      },
      "pricing-section.enterprise-header": {
        id: "pricing-section.enterprise-header",
        type: "box",
        style: { gap: "xs" },
        children: ["pricing-section.enterprise-title", "pricing-section.enterprise-body"],
      },
      "pricing-section.enterprise-title": {
        id: "pricing-section.enterprise-title",
        type: "text",
        value: "Enterprise",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "pricing-section.enterprise-body": {
        id: "pricing-section.enterprise-body",
        type: "text",
        value: "Custom controls for larger organizations.",
        style: { color: "fg-muted" },
      },
      "pricing-section.enterprise-badge": {
        id: "pricing-section.enterprise-badge",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["pricing-section.enterprise-badge-label"],
      },
      "pricing-section.enterprise-badge-label": {
        id: "pricing-section.enterprise-badge-label",
        type: "text",
        value: "Custom",
        style: { color: "fg", size: "sm", weight: "semibold" },
      },
    },
  },
  {
    name: "faq-section",
    metadata: {
      description: "A concise FAQ list for common questions.",
      category: "support",
      useWhen: "Answering several predictable questions.",
      avoidWhen: "The user needs an interactive troubleshooting flow.",
      tags: ["faq", "support", "list"],
      variants: ["compact"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "faq-section.root",
    nodes: {
      "faq-section.root": {
        id: "faq-section.root",
        type: "box",
        style: { gap: "md", pad: "lg", width: "full" },
        children: ["faq-section.title", "faq-section.list"],
      },
      "faq-section.title": {
        id: "faq-section.title",
        type: "text",
        value: "Questions",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "faq-section.list": {
        id: "faq-section.list",
        type: "list",
        items: [
          { title: "What is included?" },
          { title: "Can I cancel?" },
          { title: "How do I get support?" },
        ],
      },
    },
  },
  {
    name: "dashboard-summary",
    metadata: {
      description: "A KPI summary section with stats and status.",
      category: "dashboard",
      useWhen: "Summarizing current performance or account state.",
      avoidWhen: "The user asked for detailed raw records first.",
      tags: ["dashboard", "metrics", "summary"],
      variants: ["kpi"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "dashboard-summary.root",
    nodes: {
      "dashboard-summary.root": {
        id: "dashboard-summary.root",
        type: "box",
        style: { bg: "surface", gap: "md", pad: "lg", radius: "lg", width: "full" },
        children: [
          "dashboard-summary.title",
          "dashboard-summary.stat",
          "dashboard-summary.badge",
          "dashboard-summary.progress",
        ],
      },
      "dashboard-summary.title": {
        id: "dashboard-summary.title",
        type: "text",
        value: "Overview",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "dashboard-summary.stat": {
        id: "dashboard-summary.stat",
        type: "box",
        style: { gap: "xs" },
        children: [
          "dashboard-summary.stat-label",
          "dashboard-summary.stat-value",
          "dashboard-summary.stat-delta",
        ],
      },
      "dashboard-summary.stat-label": {
        id: "dashboard-summary.stat-label",
        type: "text",
        value: "Revenue",
        style: { color: "fg-muted", size: "sm" },
      },
      "dashboard-summary.stat-value": {
        id: "dashboard-summary.stat-value",
        type: "text",
        value: "$42k",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "dashboard-summary.stat-delta": {
        id: "dashboard-summary.stat-delta",
        type: "text",
        value: "+12%",
        style: { color: "success", size: "sm", weight: "semibold" },
      },
      "dashboard-summary.badge": {
        id: "dashboard-summary.badge",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["dashboard-summary.badge-label"],
      },
      "dashboard-summary.badge-label": {
        id: "dashboard-summary.badge-label",
        type: "text",
        value: "Healthy",
        style: { color: "success", size: "xs", weight: "semibold" },
      },
      "dashboard-summary.progress": {
        id: "dashboard-summary.progress",
        type: "progress",
        label: "Goal",
        value: 72,
        tone: "accent",
      },
    },
  },
  {
    name: "settings-panel",
    metadata: {
      description: "A settings card with two editable fields and a save action.",
      category: "settings",
      useWhen: "Collecting a small configuration update.",
      avoidWhen: "The form needs many fields or validation steps.",
      tags: ["settings", "form", "fields"],
      variants: ["compact"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "settings-panel.root",
    nodes: {
      "settings-panel.root": {
        id: "settings-panel.root",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: [
          "settings-panel.header",
          "settings-panel.email",
          "settings-panel.timezone",
          "settings-panel.save",
        ],
      },
      "settings-panel.header": {
        id: "settings-panel.header",
        type: "box",
        style: { gap: "xs" },
        children: ["settings-panel.title"],
      },
      "settings-panel.title": {
        id: "settings-panel.title",
        type: "text",
        value: "Workspace settings",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "settings-panel.email": {
        id: "settings-panel.email",
        type: "input",
        name: "email",
        input: "email",
        label: "Notification email",
        style: { width: "full" },
      },
      "settings-panel.timezone": {
        id: "settings-panel.timezone",
        type: "input",
        name: "timezone",
        input: "select",
        label: "Timezone",
        options: ["UTC", "PST", "EST"],
        style: { width: "full" },
      },
      "settings-panel.save": {
        id: "settings-panel.save",
        type: "box",
        style: { bg: "accent", pad: "sm", radius: "md", shadow: "sm" },
        children: ["settings-panel.save-label"],
        onPress: { kind: "agent", name: "save_settings", collect: "settings-panel.root" },
      },
      "settings-panel.save-label": {
        id: "settings-panel.save-label",
        type: "text",
        value: "Save settings",
        style: { color: "accent-fg", align: "center", weight: "semibold" },
      },
    },
  },
  {
    name: "feature-grid",
    metadata: {
      description: "A three-card feature grid.",
      category: "marketing",
      useWhen: "Explaining a small set of product capabilities.",
      avoidWhen: "The user needs one focused workflow.",
      tags: ["features", "grid", "cards"],
      variants: ["three-card"],
      repeatable: false,
      preferredParent: "root",
    },
    root: "feature-grid.root",
    nodes: {
      "feature-grid.root": {
        id: "feature-grid.root",
        type: "box",
        style: { gap: "md", pad: "lg", width: "full" },
        children: [
          "feature-grid.title",
          "feature-grid.first",
          "feature-grid.second",
          "feature-grid.third",
        ],
      },
      "feature-grid.title": {
        id: "feature-grid.title",
        type: "text",
        value: "Features",
        style: { color: "fg", size: "xl", weight: "bold" },
      },
      "feature-grid.first": {
        id: "feature-grid.first",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: ["feature-grid.first-header"],
      },
      "feature-grid.first-header": {
        id: "feature-grid.first-header",
        type: "box",
        style: { gap: "xs" },
        children: ["feature-grid.first-title", "feature-grid.first-body"],
      },
      "feature-grid.first-title": {
        id: "feature-grid.first-title",
        type: "text",
        value: "Fast setup",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "feature-grid.first-body": {
        id: "feature-grid.first-body",
        type: "text",
        value: "Start from safe default UI patterns.",
        style: { color: "fg-muted" },
      },
      "feature-grid.second": {
        id: "feature-grid.second",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: ["feature-grid.second-header"],
      },
      "feature-grid.second-header": {
        id: "feature-grid.second-header",
        type: "box",
        style: { gap: "xs" },
        children: ["feature-grid.second-title", "feature-grid.second-body"],
      },
      "feature-grid.second-title": {
        id: "feature-grid.second-title",
        type: "text",
        value: "Live UI",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "feature-grid.second-body": {
        id: "feature-grid.second-body",
        type: "text",
        value: "Render task-specific screens as the conversation changes.",
        style: { color: "fg-muted" },
      },
      "feature-grid.third": {
        id: "feature-grid.third",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: ["feature-grid.third-header"],
      },
      "feature-grid.third-header": {
        id: "feature-grid.third-header",
        type: "box",
        style: { gap: "xs" },
        children: ["feature-grid.third-title", "feature-grid.third-body"],
      },
      "feature-grid.third-title": {
        id: "feature-grid.third-title",
        type: "text",
        value: "Safe patches",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "feature-grid.third-body": {
        id: "feature-grid.third-body",
        type: "text",
        value: "Keep every update declarative and bounded.",
        style: { color: "fg-muted" },
      },
    },
  },
  EMPTY_STATE_COMPOSITION,
  {
    name: "support-triage",
    metadata: {
      description: "A support triage card with issue type selection.",
      category: "support",
      useWhen: "Collecting basic support context before agent follow-up.",
      avoidWhen: "The user already gave all required details.",
      tags: ["support", "triage", "form"],
      variants: ["compact"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "support-triage.root",
    nodes: {
      "support-triage.root": {
        id: "support-triage.root",
        type: "box",
        style: {
          bg: "surface",
          border: true,
          gap: "sm",
          pad: "md",
          radius: "md",
          shadow: "sm",
        },
        children: [
          "support-triage.header",
          "support-triage.issue",
          "support-triage.details",
          "support-triage.submit",
        ],
      },
      "support-triage.header": {
        id: "support-triage.header",
        type: "box",
        style: { gap: "xs" },
        children: ["support-triage.title"],
      },
      "support-triage.title": {
        id: "support-triage.title",
        type: "text",
        value: "How can we help?",
        style: { color: "fg", size: "lg", weight: "bold" },
      },
      "support-triage.issue": {
        id: "support-triage.issue",
        type: "input",
        name: "issue_type",
        input: "select",
        label: "Issue type",
        options: ["Billing", "Technical", "Account"],
        style: { width: "full" },
      },
      "support-triage.details": {
        id: "support-triage.details",
        type: "input",
        name: "details",
        input: "text",
        label: "Describe what happened",
        style: { width: "full" },
      },
      "support-triage.submit": {
        id: "support-triage.submit",
        type: "box",
        style: { bg: "accent", pad: "sm", radius: "md", shadow: "sm" },
        children: ["support-triage.submit-label"],
        onPress: { kind: "agent", name: "submit_support", collect: "support-triage.root" },
      },
      "support-triage.submit-label": {
        id: "support-triage.submit-label",
        type: "text",
        value: "Send request",
        style: { color: "accent-fg", align: "center", weight: "semibold" },
      },
    },
  },
  // --- Per-tone badge compositions (PR-5a: badge demoted to composition) ------
  // Each bakes the fully-resolved tokens the removed `badge` component rendered
  // for its tone: rendererDefault(tone) ∪ theme recipe.box/text ∪ recipe.parts.
  // The base `badge` reproduces the tone-less/`info` render (empty recipe →
  // renderer defaults only); the tone-named variants fold in their recipe.
  {
    name: "badge",
    metadata: {
      description: "A compact neutral status chip.",
      category: "feedback",
      useWhen: "Labeling a compact status, tag, or count.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "chip"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "badge.root",
    nodes: {
      "badge.root": {
        id: "badge.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["badge.label"],
      },
      "badge.label": {
        id: "badge.label",
        type: "text",
        value: "In review",
        style: { color: "fg", size: "sm", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-neutral",
    metadata: {
      description: "A compact neutral-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a compact neutral status or tag.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "neutral"],
      variants: ["neutral"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "badge-neutral.root",
    nodes: {
      "badge-neutral.root": {
        id: "badge-neutral.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
        children: ["badge-neutral.label"],
      },
      "badge-neutral.label": {
        id: "badge-neutral.label",
        type: "text",
        value: "Draft",
        style: { color: "neutral", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-success",
    metadata: {
      description: "A compact success-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a healthy, complete, or positive status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "success"],
      variants: ["success"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "badge-success.root",
    nodes: {
      "badge-success.root": {
        id: "badge-success.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-success.label"],
      },
      "badge-success.label": {
        id: "badge-success.label",
        type: "text",
        value: "Healthy",
        style: { color: "success", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-warning",
    metadata: {
      description: "A compact warning-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a caution, pending, or attention status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "warning"],
      variants: ["warning"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "badge-warning.root",
    nodes: {
      "badge-warning.root": {
        id: "badge-warning.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-warning.label"],
      },
      "badge-warning.label": {
        id: "badge-warning.label",
        type: "text",
        value: "Pending",
        style: { color: "warning", size: "xs", weight: "semibold" },
      },
    },
  },
  {
    name: "badge-danger",
    metadata: {
      description: "A compact danger-toned status chip.",
      category: "feedback",
      useWhen: "Labeling a failing, blocked, or critical status.",
      avoidWhen: "The message needs a full sentence or an action.",
      tags: ["badge", "status", "danger"],
      variants: ["danger"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "badge-danger.root",
    nodes: {
      "badge-danger.root": {
        id: "badge-danger.root",
        type: "box",
        style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
        children: ["badge-danger.label"],
      },
      "badge-danger.label": {
        id: "badge-danger.label",
        type: "text",
        value: "Failed",
        style: { color: "danger", size: "xs", weight: "semibold" },
      },
    },
  },
  // --- Per-tone alert compositions (PR-5a: alert demoted to composition) -------
  // box baked from rendererDefault ∪ recipe.box; title/body texts baked from the
  // title/body defaults ∪ recipe.text ∪ recipe.parts. Base `alert` reproduces the
  // tone-less render (empty recipe → renderer defaults only, body has no tokens).
  {
    name: "alert",
    metadata: {
      description: "A neutral notice panel with a title and body.",
      category: "feedback",
      useWhen: "Calling out a plain notice or message.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "feedback"],
      variants: ["default"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "alert.root",
    nodes: {
      "alert.root": {
        id: "alert.root",
        type: "box",
        style: { gap: "xs", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert.title", "alert.body"],
      },
      "alert.title": {
        id: "alert.title",
        type: "text",
        value: "Scheduled maintenance",
        style: { weight: "bold" },
      },
      "alert.body": {
        id: "alert.body",
        type: "text",
        value: "The dashboard will be read-only for ten minutes tonight.",
        style: {},
      },
    },
  },
  {
    name: "alert-info",
    metadata: {
      description: "An informational notice panel with a title and body.",
      category: "feedback",
      useWhen: "Sharing informational context or a tip.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "info"],
      variants: ["info"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "alert-info.root",
    nodes: {
      "alert-info.root": {
        id: "alert-info.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-info.title", "alert-info.body"],
      },
      "alert-info.title": {
        id: "alert-info.title",
        type: "text",
        value: "New export format",
        style: { weight: "bold", color: "info" },
      },
      "alert-info.body": {
        id: "alert-info.body",
        type: "text",
        value: "CSV exports now include timezone-aware date and time values.",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-success",
    metadata: {
      description: "A success notice panel with a title and body.",
      category: "feedback",
      useWhen: "Confirming a completed or successful action.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "success"],
      variants: ["success"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "alert-success.root",
    nodes: {
      "alert-success.root": {
        id: "alert-success.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-success.title", "alert-success.body"],
      },
      "alert-success.title": {
        id: "alert-success.title",
        type: "text",
        value: "Changes saved",
        style: { weight: "bold", color: "success" },
      },
      "alert-success.body": {
        id: "alert-success.body",
        type: "text",
        value: "Your workspace settings are up to date.",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-warning",
    metadata: {
      description: "A warning notice panel with a title and body.",
      category: "feedback",
      useWhen: "Warning about a caution or pending condition.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "warning"],
      variants: ["warning"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "alert-warning.root",
    nodes: {
      "alert-warning.root": {
        id: "alert-warning.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-warning.title", "alert-warning.body"],
      },
      "alert-warning.title": {
        id: "alert-warning.title",
        type: "text",
        value: "Storage almost full",
        style: { weight: "bold", color: "warning" },
      },
      "alert-warning.body": {
        id: "alert-warning.body",
        type: "text",
        value: "Remove unused files before the next scheduled import.",
        style: { color: "fg" },
      },
    },
  },
  {
    name: "alert-danger",
    metadata: {
      description: "A danger notice panel with a title and body.",
      category: "feedback",
      useWhen: "Flagging an error or critical condition.",
      avoidWhen: "The state is a compact status (use a badge).",
      tags: ["alert", "notice", "danger"],
      variants: ["danger"],
      repeatable: true,
      preferredParent: "box",
    },
    root: "alert-danger.root",
    nodes: {
      "alert-danger.root": {
        id: "alert-danger.root",
        type: "box",
        style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
        children: ["alert-danger.title", "alert-danger.body"],
      },
      "alert-danger.title": {
        id: "alert-danger.title",
        type: "text",
        value: "Payment failed",
        style: { weight: "bold", color: "danger" },
      },
      "alert-danger.body": {
        id: "alert-danger.body",
        type: "text",
        value: "Update the billing method to keep the workspace active.",
        style: { color: "fg" },
      },
    },
  },
  CHART_TABLE_VIEW_COMPOSITION,
];
