/**
 * The default Facet design-system preset.
 *
 * Core owns the Design Contract v1 token names and validation; this module owns
 * one complete set of default values for the default catalog. The object is
 * frozen plain data and imports no React.
 */

import type { FacetTheme } from "@facet/core";

export const DEFAULT_THEME: FacetTheme = Object.freeze({
  foundation: Object.freeze({
    palette: Object.freeze({
      neutral0: "#ffffff",
      neutral50: "#f8fafc",
      neutral100: "#f1f5f9",
      neutral200: "#e2e8f0",
      neutral300: "#cbd5e1",
      neutral400: "#94a3b8",
      neutral500: "#64748b",
      neutral600: "#475569",
      neutral700: "#334155",
      neutral800: "#1e293b",
      neutral900: "#0f172a",
      neutral950: "#080f1f",
      neutral1000: "#020617",
      brand50: "#eef2ff",
      brand100: "#e0e7ff",
      brand200: "#c7d2fe",
      brand300: "#a5b4fc",
      brand400: "#818cf8",
      brand500: "#6366f1",
      brand600: "#4f46e5",
      brand700: "#4338ca",
      brand800: "#3730a3",
      brand900: "#312e81",
      brand950: "#1e1b4b",
      accent50: "#ecfeff",
      accent100: "#cffafe",
      accent200: "#a5f3fc",
      accent300: "#67e8f9",
      accent400: "#22d3ee",
      accent500: "#06b6d4",
      accent600: "#0891b2",
      accent700: "#0e7490",
      accent800: "#155e75",
      accent900: "#164e63",
      accent950: "#083344",
      success50: "#ecfdf5",
      success100: "#d1fae5",
      success200: "#a7f3d0",
      success300: "#6ee7b7",
      success400: "#34d399",
      success500: "#10b981",
      success600: "#059669",
      success700: "#047857",
      success800: "#065f46",
      success900: "#064e3b",
      success950: "#022c22",
      warning50: "#fffbeb",
      warning100: "#fef3c7",
      warning200: "#fde68a",
      warning300: "#fcd34d",
      warning400: "#fbbf24",
      warning500: "#f59e0b",
      warning600: "#d97706",
      warning700: "#b45309",
      warning800: "#92400e",
      warning900: "#78350f",
      warning950: "#451a03",
      danger50: "#fef2f2",
      danger100: "#fee2e2",
      danger200: "#fecaca",
      danger300: "#fca5a5",
      danger400: "#f87171",
      danger500: "#ef4444",
      danger600: "#dc2626",
      danger700: "#b91c1c",
      danger800: "#991b1b",
      danger900: "#7f1d1d",
      danger950: "#450a0a",
      info50: "#eff6ff",
      info100: "#dbeafe",
      info200: "#bfdbfe",
      info300: "#93c5fd",
      info400: "#60a5fa",
      info500: "#3b82f6",
      info600: "#2563eb",
      info700: "#1d4ed8",
      info800: "#1e40af",
      info900: "#1e3a8a",
      info950: "#172554",
      categorical1: "#6366f1",
      categorical2: "#06b6d4",
      categorical3: "#10b981",
      categorical4: "#f59e0b",
      categorical5: "#ef4444",
      categorical6: "#8b5cf6",
      categorical7: "#14b8a6",
      categorical8: "#84cc16",
      categorical9: "#f97316",
      categorical10: "#ec4899",
      categorical11: "#0ea5e9",
      categorical12: "#64748b",
    }),
    typography: Object.freeze({
      fontFamilySans: "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      fontFamilySerif: "Georgia, Cambria, 'Times New Roman', Times, serif",
      fontFamilyMono: "ui-monospace, 'SF Mono', 'JetBrains Mono', Menlo, Consolas, monospace",
      fontFamilyDisplay:
        "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      fontSize2xs: "0.6875rem",
      fontSizeXs: "0.75rem",
      fontSizeSm: "0.875rem",
      fontSizeMd: "1rem",
      fontSizeLg: "1.125rem",
      fontSizeXl: "1.25rem",
      fontSize2xl: "1.5rem",
      fontSize3xl: "1.875rem",
      fontSize4xl: "2.25rem",
      fontSize5xl: "3rem",
      fontSize6xl: "3.75rem",
      fontWeightLight: "300",
      fontWeightRegular: "400",
      fontWeightMedium: "500",
      fontWeightSemibold: "600",
      fontWeightBold: "700",
      fontWeightBlack: "900",
      lineHeightNone: "1",
      lineHeightTight: "1.2",
      lineHeightSnug: "1.35",
      lineHeightNormal: "1.5",
      lineHeightRelaxed: "1.65",
      lineHeightLoose: "1.8",
      letterSpacingTight: "-0.01em",
      letterSpacingNormal: "0",
      letterSpacingWide: "0.04em",
    }),
    space: Object.freeze({
      none: "0",
      hairline: "1px",
      micro: "0.125rem",
      tiny: "0.25rem",
      xs: "0.5rem",
      sm: "0.75rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      xxl: "3rem",
      xxxl: "4rem",
      jumbo: "6rem",
      mega: "8rem",
    }),
    size: Object.freeze({
      iconXs: "0.75rem",
      iconSm: "1rem",
      iconMd: "1.25rem",
      iconLg: "1.5rem",
      iconXl: "2rem",
      controlHeightSm: "2rem",
      controlHeightMd: "2.5rem",
      controlHeightLg: "3rem",
      controlHeightXl: "3.5rem",
      touchTarget: "2.75rem",
      containerXs: "24rem",
      containerSm: "36rem",
      containerMd: "52rem",
      containerLg: "72rem",
      containerXl: "96rem",
      contentMeasureSm: "36rem",
      contentMeasureMd: "48rem",
      contentMeasureLg: "64rem",
    }),
    radius: Object.freeze({
      none: "0",
      xs: "0.125rem",
      sm: "0.25rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      xxl: "1.5rem",
      full: "9999px",
    }),
    borderWidth: Object.freeze({
      none: "0",
      hairline: "1px",
      thin: "1px",
      medium: "2px",
      thick: "3px",
    }),
    shadow: Object.freeze({
      none: "none",
      xs: "0 1px 1px rgba(15, 23, 42, 0.04)",
      sm: "0 1px 2px rgba(15, 23, 42, 0.08)",
      md: "0 4px 12px rgba(15, 23, 42, 0.1)",
      lg: "0 12px 32px rgba(15, 23, 42, 0.14)",
      xl: "0 24px 64px rgba(15, 23, 42, 0.18)",
      inner: "inset 0 1px 2px rgba(15, 23, 42, 0.08)",
    }),
    opacity: Object.freeze({
      transparent: "0",
      disabled: "0.45",
      muted: "0.72",
      overlay: "0.56",
      visible: "1",
    }),
    motion: Object.freeze({
      durationInstant: "0ms",
      durationFast: "120ms",
      durationNormal: "180ms",
      durationSlow: "260ms",
      durationSlower: "420ms",
      easeLinear: "linear",
      easeStandard: "cubic-bezier(0.2, 0, 0, 1)",
      easeEnter: "cubic-bezier(0, 0, 0.2, 1)",
      easeExit: "cubic-bezier(0.4, 0, 1, 1)",
      easeEmphasized: "cubic-bezier(0.2, 0, 0, 1.2)",
    }),
    effect: Object.freeze({
      blurNone: "blur(0)",
      blurSm: "blur(4px)",
      blurMd: "blur(8px)",
      blurLg: "blur(16px)",
      backdropNone: "none",
      backdropMuted: "saturate(120%) blur(8px)",
      backdropStrong: "saturate(140%) blur(16px)",
    }),
    breakpoint: Object.freeze({
      xs: "30rem",
      sm: "40rem",
      md: "48rem",
      lg: "64rem",
      xl: "80rem",
      xxl: "96rem",
    }),
    density: Object.freeze({
      compact: "0.875",
      comfortable: "1",
      spacious: "1.125",
      current: "1",
    }),
  }),
  semantic: Object.freeze({
    canvas: Object.freeze({
      background: "#ffffff",
      muted: "#f8fafc",
      inverse: "#0f172a",
    }),
    surface: Object.freeze({
      default: "#ffffff",
      muted: "#f8fafc",
      raised: "#ffffff",
      sunken: "#f1f5f9",
      inverse: "#0f172a",
      overlay: "#ffffff",
    }),
    text: Object.freeze({
      default: "#0f172a",
      muted: "#475569",
      subtle: "#64748b",
      disabled: "#94a3b8",
      inverse: "#ffffff",
      link: "#4f46e5",
      linkHover: "#4338ca",
      onAction: "#ffffff",
      onStatus: "#0f172a",
    }),
    border: Object.freeze({
      default: "#e2e8f0",
      muted: "#f1f5f9",
      strong: "#cbd5e1",
      focus: "#6366f1",
      danger: "#dc2626",
      transparent: "transparent",
    }),
    action: Object.freeze({
      primaryBg: "#4f46e5",
      primaryText: "#ffffff",
      primaryBorder: "#4f46e5",
      primaryHoverBg: "#4338ca",
      primaryActiveBg: "#3730a3",
      secondaryBg: "#ffffff",
      secondaryText: "#0f172a",
      secondaryBorder: "#cbd5e1",
      secondaryHoverBg: "#f8fafc",
      tertiaryBg: "transparent",
      tertiaryText: "#475569",
      tertiaryHoverBg: "#f1f5f9",
      destructiveBg: "#dc2626",
      destructiveText: "#ffffff",
      destructiveHoverBg: "#b91c1c",
    }),
    status: Object.freeze({
      neutralBg: "#f1f5f9",
      neutralText: "#334155",
      neutralBorder: "#cbd5e1",
      successBg: "#ecfdf5",
      successText: "#047857",
      successBorder: "#a7f3d0",
      warningBg: "#fffbeb",
      warningText: "#b45309",
      warningBorder: "#fde68a",
      dangerBg: "#fef2f2",
      dangerText: "#b91c1c",
      dangerBorder: "#fecaca",
      infoBg: "#eff6ff",
      infoText: "#1d4ed8",
      infoBorder: "#bfdbfe",
    }),
    state: Object.freeze({
      hoverBg: "#f8fafc",
      activeBg: "#f1f5f9",
      selectedBg: "#eef2ff",
      selectedText: "#312e81",
      pressedBg: "#e0e7ff",
    }),
    focus: Object.freeze({
      ringColor: "#818cf8",
      ringWidth: "3px",
      ringOffset: "2px",
      ringStyle: "solid",
    }),
    selection: Object.freeze({
      background: "#e0e7ff",
      text: "#1e1b4b",
    }),
    disabled: Object.freeze({
      background: "#f1f5f9",
      text: "#94a3b8",
      border: "#e2e8f0",
      opacity: "0.45",
    }),
    overlay: Object.freeze({
      scrim: "rgba(15, 23, 42, 0.56)",
      backdrop: "saturate(120%) blur(8px)",
      surface: "#ffffff",
      shadow: "0 24px 64px rgba(15, 23, 42, 0.18)",
    }),
    loading: Object.freeze({
      skeletonBase: "#e2e8f0",
      skeletonHighlight: "#f8fafc",
      progressTrack: "#e2e8f0",
      progressFill: "#4f46e5",
      shimmerDuration: "1.2s",
    }),
    layer: Object.freeze({
      baseShadow: "none",
      raisedShadow: "0 4px 12px rgba(15, 23, 42, 0.1)",
      popoverShadow: "0 12px 32px rgba(15, 23, 42, 0.14)",
      modalShadow: "0 24px 64px rgba(15, 23, 42, 0.18)",
      toastShadow: "0 12px 32px rgba(15, 23, 42, 0.14)",
      scrimColor: "rgba(15, 23, 42, 0.56)",
    }),
    validation: Object.freeze({
      validText: "#047857",
      validBorder: "#10b981",
      invalidText: "#b91c1c",
      invalidBorder: "#dc2626",
      requiredText: "#b45309",
      helpText: "#64748b",
      errorText: "#b91c1c",
      warningText: "#b45309",
    }),
  }),
  recipes: Object.freeze({
    screen: Object.freeze({
      background: "var(--facet-semantic-canvas-background)",
      text: "var(--facet-semantic-text-default)",
      contentGap: "var(--facet-foundation-space-lg)",
      titleColor: "var(--facet-semantic-text-default)",
      titleFontSize: "var(--facet-foundation-typography-font-size3xl)",
      titleFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
      titleLineHeight: "var(--facet-foundation-typography-line-height-tight)",
    }),
    stack: Object.freeze({
      defaultGap: "var(--facet-foundation-space-md)",
      padding: "var(--facet-foundation-space-md)",
    }),
    row: Object.freeze({
      defaultGap: "var(--facet-foundation-space-md)",
      padding: "var(--facet-foundation-space-md)",
    }),
    grid: Object.freeze({
      defaultGap: "var(--facet-foundation-space-md)",
      minColumnWidth: "16rem",
    }),
    modal: Object.freeze({
      triggerBg: "var(--facet-semantic-action-secondary-bg)",
      triggerText: "var(--facet-semantic-action-secondary-text)",
      frameBg: "var(--facet-semantic-overlay-surface)",
      frameText: "var(--facet-semantic-text-default)",
      frameBorder: "var(--facet-semantic-border-default)",
      frameRadius: "var(--facet-foundation-radius-xl)",
      frameShadow: "var(--facet-semantic-layer-modal-shadow)",
      framePadding: "var(--facet-foundation-space-lg)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    card: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      shadow: "var(--facet-semantic-layer-raised-shadow)",
      padding: "var(--facet-foundation-space-lg)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    empty: Object.freeze({
      background: "var(--facet-semantic-surface-muted)",
      text: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-xl)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    text: Object.freeze({
      titleFontSize: "var(--facet-foundation-typography-font-size3xl)",
      titleFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
      headingFontSize: "var(--facet-foundation-typography-font-size-xl)",
      headingFontWeight: "var(--facet-foundation-typography-font-weight-semibold)",
      bodyFontSize: "var(--facet-foundation-typography-font-size-md)",
      captionFontSize: "var(--facet-foundation-typography-font-size-xs)",
      defaultText: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
    }),
    metric: Object.freeze({
      valueColor: "var(--facet-semantic-text-default)",
      valueFontSize: "var(--facet-foundation-typography-font-size3xl)",
      valueFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
      labelColor: "var(--facet-semantic-text-muted)",
      labelFontSize: "var(--facet-foundation-typography-font-size-sm)",
    }),
    badge: Object.freeze({
      background: "var(--facet-semantic-status-neutral-bg)",
      text: "var(--facet-semantic-status-neutral-text)",
      border: "var(--facet-semantic-status-neutral-border)",
      radius: "var(--facet-foundation-radius-full)",
      paddingInline: "var(--facet-foundation-space-xs)",
      paddingBlock: "var(--facet-foundation-space-tiny)",
    }),
    button: Object.freeze({
      primaryBg: "var(--facet-semantic-action-primary-bg)",
      primaryText: "var(--facet-semantic-action-primary-text)",
      primaryBorder: "var(--facet-semantic-action-primary-border)",
      secondaryBg: "var(--facet-semantic-action-secondary-bg)",
      secondaryText: "var(--facet-semantic-action-secondary-text)",
      secondaryBorder: "var(--facet-semantic-action-secondary-border)",
      quietText: "var(--facet-semantic-action-tertiary-text)",
      radius: "var(--facet-foundation-radius-md)",
      paddingInline: "var(--facet-foundation-space-md)",
      paddingBlock: "var(--facet-foundation-space-xs)",
      focusRing: "0 0 0 3px var(--facet-semantic-focus-ring-color)",
    }),
    field: Object.freeze({
      labelText: "var(--facet-semantic-text-default)",
      inputBg: "var(--facet-semantic-surface-default)",
      inputText: "var(--facet-semantic-text-default)",
      inputBorder: "var(--facet-semantic-border-default)",
      inputFocusBorder: "var(--facet-semantic-border-focus)",
      inputRadius: "var(--facet-foundation-radius-sm)",
      inputPadding: "var(--facet-foundation-space-xs)",
    }),
    table: Object.freeze({
      captionText: "var(--facet-semantic-text-muted)",
      text: "var(--facet-semantic-text-default)",
      headerText: "var(--facet-semantic-text-muted)",
      headerBg: "var(--facet-semantic-surface-muted)",
      rowBorder: "var(--facet-semantic-border-default)",
      cellPadding: "var(--facet-foundation-space-sm)",
    }),
  }),
});
