/**
 * The default Facet design-system preset.
 *
 * Core owns the Design Contract v1 token names and validation; this module owns
 * one complete set of default values for the default catalog. The object is
 * frozen plain data and imports no React.
 */

import type { FacetTheme } from "@facet/core";

export const DEFAULT_THEME: FacetTheme = Object.freeze({
  foundation: Object.freeze({
    palette: Object.freeze({
      neutral0: "#fffdf7",
      neutral50: "#fbf2df",
      neutral100: "#f6ead2",
      neutral200: "#e3d5b8",
      neutral300: "#ccb990",
      neutral400: "#aa9774",
      neutral500: "#82755f",
      neutral600: "#6f6654",
      neutral700: "#4b4437",
      neutral800: "#302a22",
      neutral900: "#171410",
      neutral950: "#0b0907",
      neutral1000: "#050403",
      brand50: "#edf7ff",
      brand100: "#d8edff",
      brand200: "#b7dcff",
      brand300: "#86c5ff",
      brand400: "#5ca9f4",
      brand500: "#2f6fc8",
      brand600: "#255fac",
      brand700: "#1d4d8f",
      brand800: "#173a6e",
      brand900: "#10294f",
      brand950: "#0b1a36",
      accent50: "#fff9cc",
      accent100: "#fff1a6",
      accent200: "#ffe266",
      accent300: "#ffd23d",
      accent400: "#ffc329",
      accent500: "#ffa62b",
      accent600: "#f06f24",
      accent700: "#cc4e1d",
      accent800: "#9c3518",
      accent900: "#6e2414",
      accent950: "#3a1109",
      success50: "#ecfdf5",
      success100: "#d1fae5",
      success200: "#a7f3d0",
      success300: "#6ee7b7",
      success400: "#34d399",
      success500: "#10b981",
      success600: "#059669",
      success700: "#047857",
      success800: "#065f46",
      success900: "#064e3b",
      success950: "#022c22",
      warning50: "#fffbeb",
      warning100: "#fef3c7",
      warning200: "#fde68a",
      warning300: "#fcd34d",
      warning400: "#fbbf24",
      warning500: "#f59e0b",
      warning600: "#d97706",
      warning700: "#b45309",
      warning800: "#92400e",
      warning900: "#78350f",
      warning950: "#451a03",
      danger50: "#fef2f2",
      danger100: "#fee2e2",
      danger200: "#fecaca",
      danger300: "#fca5a5",
      danger400: "#f87171",
      danger500: "#ef4444",
      danger600: "#dc2626",
      danger700: "#b91c1c",
      danger800: "#991b1b",
      danger900: "#7f1d1d",
      danger950: "#450a0a",
      info50: "#eff6ff",
      info100: "#dbeafe",
      info200: "#bfdbfe",
      info300: "#93c5fd",
      info400: "#60a5fa",
      info500: "#3b82f6",
      info600: "#2563eb",
      info700: "#1d4ed8",
      info800: "#1e40af",
      info900: "#1e3a8a",
      info950: "#172554",
      categorical1: "#2f6fc8",
      categorical2: "#ffc329",
      categorical3: "#2f8f6b",
      categorical4: "#f06f24",
      categorical5: "#e14f3b",
      categorical6: "#86c5ff",
      categorical7: "#5c7a35",
      categorical8: "#fff1a6",
      categorical9: "#cc4e1d",
      categorical10: "#e889a6",
      categorical11: "#255fac",
      categorical12: "#82755f",
    }),
    typography: Object.freeze({
      fontFamilySans: "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      fontFamilySerif: "Georgia, Cambria, 'Times New Roman', Times, serif",
      fontFamilyMono: "ui-monospace, 'SF Mono', 'JetBrains Mono', Menlo, Consolas, monospace",
      fontFamilyDisplay:
        "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      fontSize2xs: "0.6875rem",
      fontSizeXs: "0.75rem",
      fontSizeSm: "0.875rem",
      fontSizeMd: "1rem",
      fontSizeLg: "1.125rem",
      fontSizeXl: "1.25rem",
      fontSize2xl: "1.5rem",
      fontSize3xl: "1.875rem",
      fontSize4xl: "2.25rem",
      fontSize5xl: "3rem",
      fontSize6xl: "3.75rem",
      fontWeightLight: "300",
      fontWeightRegular: "400",
      fontWeightMedium: "500",
      fontWeightSemibold: "600",
      fontWeightBold: "700",
      fontWeightBlack: "900",
      lineHeightNone: "1",
      lineHeightTight: "1.2",
      lineHeightSnug: "1.35",
      lineHeightNormal: "1.5",
      lineHeightRelaxed: "1.65",
      lineHeightLoose: "1.8",
      letterSpacingTight: "0",
      letterSpacingNormal: "0",
      letterSpacingWide: "0",
    }),
    space: Object.freeze({
      none: "0",
      hairline: "1px",
      micro: "0.125rem",
      tiny: "0.25rem",
      xs: "0.5rem",
      sm: "0.75rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      xxl: "3rem",
      xxxl: "4rem",
      jumbo: "6rem",
      mega: "8rem",
    }),
    size: Object.freeze({
      iconXs: "0.75rem",
      iconSm: "1rem",
      iconMd: "1.25rem",
      iconLg: "1.5rem",
      iconXl: "2rem",
      controlHeightSm: "2rem",
      controlHeightMd: "2.5rem",
      controlHeightLg: "3rem",
      controlHeightXl: "3.5rem",
      touchTarget: "2.75rem",
      containerXs: "24rem",
      containerSm: "36rem",
      containerMd: "52rem",
      containerLg: "72rem",
      containerXl: "96rem",
      contentMeasureSm: "36rem",
      contentMeasureMd: "48rem",
      contentMeasureLg: "64rem",
    }),
    radius: Object.freeze({
      none: "0",
      xs: "0.125rem",
      sm: "0.25rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      xxl: "1.5rem",
      full: "9999px",
    }),
    borderWidth: Object.freeze({
      none: "0",
      hairline: "1px",
      thin: "1px",
      medium: "2px",
      thick: "3px",
    }),
    shadow: Object.freeze({
      none: "none",
      xs: "0 1px 1px rgba(15, 23, 42, 0.04)",
      sm: "0 1px 2px rgba(15, 23, 42, 0.08)",
      md: "0 4px 12px rgba(15, 23, 42, 0.1)",
      lg: "0 12px 32px rgba(15, 23, 42, 0.14)",
      xl: "0 24px 64px rgba(15, 23, 42, 0.18)",
      inner: "inset 0 1px 2px rgba(15, 23, 42, 0.08)",
    }),
    opacity: Object.freeze({
      transparent: "0",
      disabled: "0.45",
      muted: "0.72",
      overlay: "0.56",
      visible: "1",
    }),
    motion: Object.freeze({
      durationInstant: "0ms",
      durationFast: "120ms",
      durationNormal: "180ms",
      durationSlow: "260ms",
      durationSlower: "420ms",
      easeLinear: "linear",
      easeStandard: "cubic-bezier(0.2, 0, 0, 1)",
      easeEnter: "cubic-bezier(0, 0, 0.2, 1)",
      easeExit: "cubic-bezier(0.4, 0, 1, 1)",
      easeEmphasized: "cubic-bezier(0.2, 0, 0, 1.2)",
    }),
    effect: Object.freeze({
      blurNone: "blur(0)",
      blurSm: "blur(4px)",
      blurMd: "blur(8px)",
      blurLg: "blur(16px)",
      backdropNone: "none",
      backdropMuted: "saturate(120%) blur(8px)",
      backdropStrong: "saturate(140%) blur(16px)",
    }),
    breakpoint: Object.freeze({
      xs: "30rem",
      sm: "40rem",
      md: "48rem",
      lg: "64rem",
      xl: "80rem",
      xxl: "96rem",
    }),
    density: Object.freeze({
      compact: "0.875",
      comfortable: "1",
      spacious: "1.125",
      current: "1",
    }),
  }),
  semantic: Object.freeze({
    canvas: Object.freeze({
      background: "#fbf2df",
      muted: "#f6ead2",
      inverse: "#0b0907",
    }),
    surface: Object.freeze({
      default: "#fffdf7",
      muted: "#f6ead2",
      raised: "#fffaf0",
      sunken: "#efe2ca",
      inverse: "#171410",
      overlay: "#fffdf7",
    }),
    text: Object.freeze({
      default: "#171410",
      muted: "#6f6654",
      subtle: "#82755f",
      disabled: "#aa9774",
      inverse: "#fffdf7",
      link: "#255fac",
      linkHover: "#1d4d8f",
      onAction: "#fffdf7",
      onStatus: "#171410",
    }),
    border: Object.freeze({
      default: "#e3d5b8",
      muted: "#efe2ca",
      strong: "#ccb990",
      focus: "#2f6fc8",
      danger: "#dc2626",
      transparent: "transparent",
    }),
    action: Object.freeze({
      primaryBg: "#2f6fc8",
      primaryText: "#fffdf7",
      primaryBorder: "#2f6fc8",
      primaryHoverBg: "#255fac",
      primaryActiveBg: "#1d4d8f",
      secondaryBg: "#fffdf7",
      secondaryText: "#171410",
      secondaryBorder: "#302a22",
      secondaryHoverBg: "#f6ead2",
      tertiaryBg: "transparent",
      tertiaryText: "#475569",
      tertiaryHoverBg: "#f1f5f9",
      destructiveBg: "#dc2626",
      destructiveText: "#fffdf7",
      destructiveHoverBg: "#b91c1c",
    }),
    status: Object.freeze({
      neutralBg: "#f6ead2",
      neutralText: "#4b4437",
      neutralBorder: "#ccb990",
      successBg: "#ecfdf5",
      successText: "#047857",
      successBorder: "#a7f3d0",
      warningBg: "#fffbeb",
      warningText: "#b45309",
      warningBorder: "#fde68a",
      dangerBg: "#fef2f2",
      dangerText: "#b91c1c",
      dangerBorder: "#fecaca",
      infoBg: "#edf7ff",
      infoText: "#1d4d8f",
      infoBorder: "#b7dcff",
    }),
    state: Object.freeze({
      hoverBg: "#fffaf0",
      activeBg: "#f6ead2",
      selectedBg: "#d8edff",
      selectedText: "#10294f",
      pressedBg: "#b7dcff",
    }),
    focus: Object.freeze({
      ringColor: "#2f6fc8",
      ringWidth: "3px",
      ringOffset: "2px",
      ringStyle: "solid",
    }),
    selection: Object.freeze({
      background: "#d8edff",
      text: "#0b1a36",
    }),
    disabled: Object.freeze({
      background: "#efe2ca",
      text: "#aa9774",
      border: "#e3d5b8",
      opacity: "0.45",
    }),
    overlay: Object.freeze({
      scrim: "rgba(23, 20, 16, 0.56)",
      backdrop: "saturate(120%) blur(8px)",
      surface: "#fffdf7",
      shadow: "0 24px 64px rgba(23, 20, 16, 0.18)",
    }),
    loading: Object.freeze({
      skeletonBase: "#e3d5b8",
      skeletonHighlight: "#fffaf0",
      progressTrack: "#e3d5b8",
      progressFill: "#2f6fc8",
      shimmerDuration: "1.2s",
    }),
    layer: Object.freeze({
      baseShadow: "none",
      raisedShadow: "0 4px 12px rgba(23, 20, 16, 0.1)",
      popoverShadow: "0 12px 32px rgba(23, 20, 16, 0.14)",
      modalShadow: "0 24px 64px rgba(23, 20, 16, 0.18)",
      toastShadow: "0 12px 32px rgba(23, 20, 16, 0.14)",
      scrimColor: "rgba(23, 20, 16, 0.56)",
    }),
    validation: Object.freeze({
      validText: "#047857",
      validBorder: "#10b981",
      invalidText: "#b91c1c",
      invalidBorder: "#dc2626",
      requiredText: "#b45309",
      helpText: "#82755f",
      errorText: "#b91c1c",
      warningText: "#b45309",
    }),
  }),
  recipes: Object.freeze({
    screen: Object.freeze({
      background: "var(--facet-semantic-canvas-background)",
      text: "var(--facet-semantic-text-default)",
      contentGap: "var(--facet-foundation-space-lg)",
      titleColor: "var(--facet-semantic-text-default)",
      titleFontSize: "var(--facet-foundation-typography-font-size3xl)",
      titleFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
      titleLineHeight: "var(--facet-foundation-typography-line-height-tight)",
    }),
    "app-shell": Object.freeze({
      defaultGap: "var(--facet-foundation-space-lg)",
      mainMinWidth: "18rem",
      minHeight: "32rem",
    }),
    stack: Object.freeze({
      defaultGap: "var(--facet-foundation-space-md)",
      padding: "var(--facet-foundation-space-md)",
    }),
    row: Object.freeze({
      defaultGap: "var(--facet-foundation-space-md)",
      padding: "var(--facet-foundation-space-md)",
    }),
    split: Object.freeze({
      defaultGap: "var(--facet-foundation-space-lg)",
      minColumnWidth: "18rem",
    }),
    grid: Object.freeze({
      defaultGap: "var(--facet-foundation-space-md)",
      minColumnWidth: "16rem",
    }),
    modal: Object.freeze({
      frameText: "var(--facet-semantic-text-default)",
    }),
    card: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      shadow: "var(--facet-semantic-layer-raised-shadow)",
      padding: "var(--facet-foundation-space-lg)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    empty: Object.freeze({
      background: "var(--facet-semantic-surface-muted)",
      text: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-xl)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    navigation: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      paddingBlock: "var(--facet-foundation-space-md)",
      paddingInline: "var(--facet-foundation-space-xl)",
      gap: "var(--facet-foundation-space-md)",
    }),
    "navigation-item": Object.freeze({
      background: "transparent",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "transparent",
      activeBg: "var(--facet-semantic-state-selected-bg)",
      activeText: "var(--facet-semantic-state-selected-text)",
      activeBorder: "var(--facet-semantic-border-focus)",
      radius: "var(--facet-foundation-radius-md)",
      paddingBlock: "var(--facet-foundation-space-xs)",
      paddingInline: "var(--facet-foundation-space-sm)",
      gap: "var(--facet-foundation-space-sm)",
      focusRing: "none",
    }),
    "action-group": Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-sm)",
      gap: "var(--facet-foundation-space-sm)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    "action-bar": Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-sm)",
      gap: "var(--facet-foundation-space-sm)",
    }),
    section: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-transparent)",
      radius: "var(--facet-foundation-radius-xl)",
      padding: "var(--facet-foundation-space-xl)",
      titleFontSize: "var(--facet-foundation-typography-font-size2xl)",
      titleFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
    }),
    divider: Object.freeze({
      color: "var(--facet-semantic-border-default)",
      text: "var(--facet-semantic-text-subtle)",
      gap: "var(--facet-foundation-space-md)",
    }),
    icon: Object.freeze({
      defaultText: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      accentText: "var(--facet-semantic-text-link)",
    }),
    avatar: Object.freeze({
      background: "var(--facet-foundation-palette-brand600)",
      text: "var(--facet-semantic-text-inverse)",
      border: "var(--facet-foundation-palette-brand700)",
      radius: "var(--facet-foundation-radius-full)",
      size: "var(--facet-foundation-size-control-height-xl)",
      fontSize: "var(--facet-foundation-typography-font-size-xl)",
      fontWeight: "var(--facet-foundation-typography-font-weight-bold)",
    }),
    image: Object.freeze({
      background: "var(--facet-semantic-surface-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
    }),
    "metric-group": Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      gap: "var(--facet-foundation-space-md)",
    }),
    chart: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      grid: "var(--facet-semantic-border-muted)",
      series: "var(--facet-foundation-palette-brand500)",
      fill: "var(--facet-foundation-palette-brand100)",
      radius: "var(--facet-foundation-radius-lg)",
    }),
    list: Object.freeze({
      text: "var(--facet-semantic-text-default)",
      markerText: "var(--facet-semantic-text-link)",
      titleColor: "var(--facet-semantic-text-default)",
      gap: "var(--facet-foundation-space-sm)",
    }),
    header: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      padding: "var(--facet-foundation-space-lg)",
      gap: "var(--facet-foundation-space-md)",
      titleFontSize: "var(--facet-foundation-typography-font-size3xl)",
      titleFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
    }),
    collection: Object.freeze({
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      titleColor: "var(--facet-semantic-text-default)",
      gap: "var(--facet-foundation-space-lg)",
      itemGap: "var(--facet-foundation-space-md)",
    }),
    "item-card": Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-md)",
      gap: "var(--facet-foundation-space-sm)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    detail: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-lg)",
      gap: "var(--facet-foundation-space-md)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    "property-list": Object.freeze({
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      gap: "var(--facet-foundation-space-md)",
    }),
    property: Object.freeze({
      labelText: "var(--facet-semantic-text-muted)",
      valueText: "var(--facet-semantic-text-default)",
      gap: "var(--facet-foundation-space-xs)",
    }),
    timeline: Object.freeze({
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      line: "var(--facet-semantic-border-strong)",
      markerBg: "var(--facet-foundation-palette-accent400)",
      markerText: "var(--facet-semantic-text-default)",
      gap: "var(--facet-foundation-space-md)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    board: Object.freeze({
      text: "var(--facet-semantic-text-default)",
      titleColor: "var(--facet-semantic-text-default)",
      gap: "var(--facet-foundation-space-md)",
    }),
    alert: Object.freeze({
      background: "var(--facet-semantic-status-info-bg)",
      text: "var(--facet-semantic-status-info-text)",
      border: "var(--facet-semantic-status-info-border)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-md)",
      titleColor: "var(--facet-semantic-status-info-text)",
    }),
    progress: Object.freeze({
      labelText: "var(--facet-semantic-text-default)",
      valueText: "var(--facet-semantic-text-muted)",
      track: "var(--facet-semantic-loading-progress-track)",
      fill: "var(--facet-semantic-loading-progress-fill)",
      radius: "var(--facet-foundation-radius-full)",
      height: "var(--facet-foundation-space-xs)",
    }),
    "board-column": Object.freeze({
      background: "var(--facet-semantic-surface-muted)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-md)",
      gap: "var(--facet-foundation-space-sm)",
    }),
    text: Object.freeze({
      titleFontSize: "var(--facet-foundation-typography-font-size3xl)",
      titleFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
      headingFontSize: "var(--facet-foundation-typography-font-size-xl)",
      headingFontWeight: "var(--facet-foundation-typography-font-weight-semibold)",
      bodyFontSize: "var(--facet-foundation-typography-font-size-md)",
      captionFontSize: "var(--facet-foundation-typography-font-size-xs)",
      defaultText: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
    }),
    metric: Object.freeze({
      valueColor: "var(--facet-semantic-text-default)",
      valueFontSize: "var(--facet-foundation-typography-font-size3xl)",
      valueFontWeight: "var(--facet-foundation-typography-font-weight-bold)",
      labelColor: "var(--facet-semantic-text-muted)",
      labelFontSize: "var(--facet-foundation-typography-font-size-sm)",
    }),
    badge: Object.freeze({
      background: "var(--facet-semantic-status-neutral-bg)",
      text: "var(--facet-semantic-status-neutral-text)",
      border: "var(--facet-semantic-status-neutral-border)",
      radius: "var(--facet-foundation-radius-full)",
      paddingInline: "var(--facet-foundation-space-xs)",
      paddingBlock: "var(--facet-foundation-space-tiny)",
    }),
    button: Object.freeze({
      primaryBg: "var(--facet-semantic-action-primary-bg)",
      primaryText: "var(--facet-semantic-action-primary-text)",
      primaryBorder: "var(--facet-semantic-action-primary-border)",
      secondaryBg: "var(--facet-semantic-action-secondary-bg)",
      secondaryText: "var(--facet-semantic-action-secondary-text)",
      secondaryBorder: "var(--facet-semantic-action-secondary-border)",
      quietText: "var(--facet-semantic-action-tertiary-text)",
      radius: "var(--facet-foundation-radius-full)",
      paddingInline: "var(--facet-foundation-space-lg)",
      paddingBlock: "var(--facet-foundation-space-xs)",
      focusRing: "none",
    }),
    field: Object.freeze({
      labelText: "var(--facet-semantic-text-default)",
      inputBg: "var(--facet-semantic-surface-default)",
      inputText: "var(--facet-semantic-text-default)",
      inputBorder: "var(--facet-semantic-border-default)",
      inputFocusBorder: "var(--facet-semantic-border-focus)",
      inputRadius: "var(--facet-foundation-radius-sm)",
      inputPadding: "var(--facet-foundation-space-xs)",
      focusRing: "none",
    }),
    table: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      captionText: "var(--facet-semantic-text-muted)",
      text: "var(--facet-semantic-text-default)",
      headerText: "var(--facet-semantic-text-muted)",
      headerBg: "var(--facet-semantic-surface-muted)",
      rowBorder: "var(--facet-semantic-border-default)",
      cellPadding: "var(--facet-foundation-space-sm)",
    }),
    calendar: Object.freeze({
      background: "var(--facet-semantic-surface-default)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      accent: "var(--facet-semantic-state-selected-bg)",
      radius: "var(--facet-foundation-radius-lg)",
      gap: "var(--facet-foundation-space-sm)",
    }),
    result: Object.freeze({
      background: "var(--facet-semantic-surface-muted)",
      text: "var(--facet-semantic-text-default)",
      mutedText: "var(--facet-semantic-text-muted)",
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      padding: "var(--facet-foundation-space-lg)",
      titleColor: "var(--facet-semantic-text-default)",
    }),
    form: Object.freeze({
      gap: "var(--facet-foundation-space-md)",
      inlineGap: "var(--facet-foundation-space-sm)",
    }),
    select: Object.freeze({
      labelText: "var(--facet-semantic-text-default)",
      inputBg: "var(--facet-semantic-surface-default)",
      inputText: "var(--facet-semantic-text-default)",
      inputBorder: "var(--facet-semantic-border-default)",
      inputFocusBorder: "var(--facet-semantic-border-focus)",
      inputRadius: "var(--facet-foundation-radius-sm)",
      inputPadding: "var(--facet-foundation-space-xs)",
      focusRing: "none",
    }),
    "choice-group": Object.freeze({
      labelText: "var(--facet-semantic-text-default)",
      optionText: "var(--facet-semantic-text-default)",
      optionBorder: "var(--facet-semantic-border-default)",
      selectedBg: "var(--facet-semantic-state-selected-bg)",
      selectedBorder: "var(--facet-semantic-border-focus)",
      radius: "var(--facet-foundation-radius-md)",
      gap: "var(--facet-foundation-space-sm)",
      focusRing: "none",
    }),
    toggle: Object.freeze({
      labelText: "var(--facet-semantic-text-default)",
      trackOff: "var(--facet-semantic-disabled-background)",
      trackOn: "var(--facet-semantic-action-primary-bg)",
      thumb: "var(--facet-semantic-surface-default)",
      focusRing: "none",
    }),
    "message-thread": Object.freeze({
      incomingBg: "var(--facet-semantic-surface-muted)",
      incomingText: "var(--facet-semantic-text-default)",
      outgoingBg: "var(--facet-semantic-state-selected-bg)",
      outgoingText: "var(--facet-semantic-state-selected-text)",
      mutedText: "var(--facet-semantic-text-muted)",
      radius: "var(--facet-foundation-radius-lg)",
      gap: "var(--facet-foundation-space-md)",
    }),
    accordion: Object.freeze({
      border: "var(--facet-semantic-border-default)",
      radius: "var(--facet-foundation-radius-lg)",
      divider: "var(--facet-semantic-border-muted)",
    }),
    "accordion-item": Object.freeze({
      summaryText: "var(--facet-semantic-text-default)",
      bodyText: "var(--facet-semantic-text-muted)",
      focusRing: "none",
      gap: "var(--facet-foundation-space-sm)",
    }),
  }),
});
