import type { BrickStyleDefinitionMap, FacetPresets } from "@facet/core";

/** Theme-owned baseline for every Brick and every published nested style target. */
export const DEFAULT_BRICK_STYLES = {
  box: {
    direction: "column",
    gap: "none",
    padding: "none",
    alignItems: "stretch",
    justifyContent: "start",
    wrap: false,
    columns: "none",
    grow: false,
    width: "auto",
    minHeight: "auto",
    maxWidth: "none",
    scroll: "none",
    sticky: false,
    color: "inherit",
    backgroundGradient: "none",
    borderWidth: "none",
    borderRadius: "none",
    shadow: "none",
    backdropScrim: "none",
    enterAnimation: "none",
  },
  text: {
    fontFamily: "sans",
    fontSize: "md",
    fontWeight: "regular",
    fontStyle: "normal",
    color: "inherit",
    textAlign: "start",
    letterSpacing: "normal",
    lineHeight: "normal",
    textWrap: "wrap",
    lineClamp: "none",
    highlight: "none",
  },
  media: {
    width: "full",
    aspectRatio: "auto",
    objectFit: "cover",
    objectPosition: "center",
    iconSize: "md",
    padding: "none",
    background: "surface",
    color: "foreground",
    borderColor: "border",
    borderWidth: "none",
    borderRadius: "none",
  },
  input: {
    width: "full",
    gap: "xs",
    label: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "medium",
      color: "foreground",
      lineHeight: "normal",
    },
    control: {
      fontFamily: "sans",
      fontSize: "md",
      fontWeight: "regular",
      color: "foreground",
      lineHeight: "normal",
      background: "background",
      borderColor: "border",
      borderWidth: "thin",
      borderRadius: "sm",
      shadow: "none",
      padding: "sm",
      controlHeight: "md",
      hover: { borderColor: "accent" },
      focus: { borderColor: "focusRing", borderWidth: "medium", shadow: "sm" },
    },
    placeholder: { color: "mutedForeground", fontStyle: "normal" },
    indicator: {
      color: "accentForeground",
      background: "background",
      borderColor: "border",
      borderWidth: "thin",
      borderRadius: "sm",
      indicatorSize: "md",
      checked: { color: "accentForeground", background: "accent", borderColor: "accent" },
      focus: { borderColor: "focusRing", borderWidth: "medium" },
    },
    option: {
      gap: "xs",
      fontFamily: "sans",
      fontSize: "md",
      fontWeight: "regular",
      color: "foreground",
      lineHeight: "normal",
      checked: { color: "accent", fontWeight: "semibold" },
      hover: { color: "accent", fontWeight: "medium" },
    },
  },
  richtext: {
    fontFamily: "sans",
    fontSize: "md",
    fontWeight: "regular",
    fontStyle: "normal",
    color: "foreground",
    textAlign: "start",
    letterSpacing: "normal",
    lineHeight: "relaxed",
    textWrap: "wrap",
    lineClamp: "none",
    blockGap: "md",
    heading1: {
      fontFamily: "sans",
      fontSize: "3xl",
      fontWeight: "bold",
      color: "foreground",
      letterSpacing: "tight",
      lineHeight: "tight",
    },
    heading2: {
      fontFamily: "sans",
      fontSize: "2xl",
      fontWeight: "bold",
      color: "foreground",
      letterSpacing: "tight",
      lineHeight: "tight",
    },
    heading3: {
      fontFamily: "sans",
      fontSize: "xl",
      fontWeight: "semibold",
      color: "foreground",
      lineHeight: "tight",
    },
    quote: {
      fontFamily: "serif",
      fontSize: "lg",
      fontStyle: "italic",
      color: "mutedForeground",
      lineHeight: "relaxed",
      background: "mutedSurface",
      padding: "md",
      borderColor: "border",
      borderWidth: "thin",
    },
    code: {
      fontFamily: "mono",
      fontSize: "sm",
      fontWeight: "regular",
      color: "foreground",
      lineHeight: "normal",
      background: "mutedSurface",
      padding: "sm",
      borderRadius: "sm",
    },
    link: {
      fontFamily: "sans",
      fontSize: "md",
      fontWeight: "medium",
      color: "accent",
      lineHeight: "normal",
      highlight: "none",
      hover: { color: "accent", highlight: "accent" },
      pressed: { color: "accent", highlight: "none" },
      focus: { color: "accent", highlight: "accent" },
    },
    listMarker: { color: "mutedForeground", fontSize: "md", fontWeight: "semibold" },
  },
  table: {
    width: "full",
    background: "surface",
    color: "foreground",
    borderColor: "border",
    borderWidth: "thin",
    borderRadius: "md",
    shadow: "none",
    caption: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "semibold",
      color: "foreground",
      lineHeight: "normal",
      textWrap: "wrap",
      lineClamp: "none",
      padding: "sm",
      background: "surface",
    },
    header: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "semibold",
      color: "foreground",
      lineHeight: "normal",
      textWrap: "nowrap",
      lineClamp: "none",
      padding: "sm",
      background: "mutedSurface",
      borderColor: "border",
      borderWidth: "thin",
      hover: { background: "accentSurface", color: "foreground", borderColor: "accent" },
      pressed: { background: "accentSurface", color: "accent", borderColor: "accent" },
      focus: { borderColor: "focusRing", borderWidth: "medium" },
      sorted: { background: "accentSurface", color: "accent", fontWeight: "bold" },
    },
    row: {
      background: "surface",
      color: "foreground",
      borderColor: "border",
      borderWidth: "thin",
      alternate: { background: "mutedSurface", color: "foreground" },
      hover: { background: "accentSurface", color: "foreground" },
    },
    cell: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "regular",
      color: "foreground",
      lineHeight: "normal",
      textWrap: "nowrap",
      lineClamp: "none",
      padding: "sm",
      borderColor: "border",
      borderWidth: "thin",
    },
  },
  chart: {
    width: "full",
    gap: "md",
    padding: "md",
    background: "surface",
    borderColor: "border",
    borderWidth: "thin",
    borderRadius: "md",
    shadow: "sm",
    title: {
      fontFamily: "sans",
      fontSize: "lg",
      fontWeight: "semibold",
      color: "foreground",
      lineHeight: "tight",
    },
    plot: {
      background: "mutedSurface",
      borderColor: "border",
      borderWidth: "none",
      borderRadius: "sm",
      axisColor: "border",
      gridColor: "border",
      labelColor: "mutedForeground",
    },
    series: {
      color1: "chart1",
      color2: "chart2",
      color3: "chart3",
      color4: "chart4",
      color5: "chart5",
      color6: "chart6",
      thickness: "md",
    },
  },
  list: {
    gap: "sm",
    padding: "none",
    color: "foreground",
    borderWidth: "none",
    borderRadius: "none",
    item: {
      gap: "xs",
      padding: "sm",
      background: "surface",
      borderColor: "border",
      borderWidth: "thin",
      borderRadius: "md",
    },
    title: {
      fontFamily: "sans",
      fontSize: "md",
      fontWeight: "semibold",
      color: "foreground",
      lineHeight: "normal",
      textWrap: "wrap",
      lineClamp: "none",
    },
    body: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "regular",
      color: "mutedForeground",
      lineHeight: "normal",
      textWrap: "wrap",
      lineClamp: "none",
    },
    marker: { color: "accent", fontSize: "sm", fontWeight: "bold" },
  },
  keyValue: {
    gap: "sm",
    padding: "md",
    background: "surface",
    color: "foreground",
    borderColor: "border",
    borderWidth: "thin",
    borderRadius: "md",
    item: {
      gap: "md",
      padding: "xs",
      borderColor: "border",
      borderWidth: "none",
    },
    label: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "regular",
      color: "mutedForeground",
      lineHeight: "normal",
    },
    value: {
      fontFamily: "sans",
      fontSize: "md",
      fontWeight: "semibold",
      color: "foreground",
      lineHeight: "normal",
    },
  },
  progress: {
    width: "full",
    gap: "xs",
    label: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "medium",
      color: "mutedForeground",
      lineHeight: "normal",
    },
    track: {
      background: "mutedSurface",
      height: "md",
      borderColor: "border",
      borderWidth: "none",
      borderRadius: "full",
    },
    fill: { background: "accent", backgroundGradient: "none", borderRadius: "full" },
  },
  loading: {
    direction: "row",
    gap: "sm",
    alignItems: "center",
    indicator: { size: "md", color: "accent", animation: "pulse" },
    label: {
      fontFamily: "sans",
      fontSize: "sm",
      fontWeight: "regular",
      color: "mutedForeground",
      lineHeight: "normal",
    },
  },
} satisfies BrickStyleDefinitionMap;

/** Discoverable single-Brick roles. Structure remains the Pattern's concern. */
export const PRESETS = {
  box: {
    panel: {
      description: "A quiet bordered surface for grouped content.",
      useWhen: "Use for cards, settings groups, and contained information.",
      avoidWhen: "Avoid for an ungrouped flow where no surface is needed.",
      style: {
        gap: "md",
        padding: "md",
        background: "surface",
        borderColor: "border",
        borderWidth: "thin",
        borderRadius: "md",
        shadow: "sm",
      },
    },
    inset: {
      description: "A subdued inset surface inside a larger region.",
      useWhen: "Use to separate secondary content without adding elevation.",
      style: { gap: "sm", padding: "md", background: "mutedSurface", borderRadius: "md" },
    },
    primaryAction: {
      description: "The strongest pressable action treatment.",
      useWhen: "Use for the single main action in a nearby decision group.",
      avoidWhen: "Avoid for secondary, destructive, or non-pressable content.",
      style: {
        direction: "row",
        gap: "xs",
        padding: "sm",
        alignItems: "center",
        justifyContent: "center",
        width: "fit",
        background: "accent",
        color: "accentForeground",
        borderColor: "accent",
        borderWidth: "thin",
        borderRadius: "md",
        shadow: "sm",
        hover: { background: "accent", color: "accentForeground", shadow: "md" },
        pressed: { background: "accent", color: "accentForeground", shadow: "none" },
        focus: { borderColor: "focusRing", borderWidth: "medium", shadow: "sm" },
      },
    },
    secondaryAction: {
      description: "A lower-emphasis pressable action treatment.",
      useWhen: "Use for supporting actions beside a primary action.",
      style: {
        direction: "row",
        gap: "xs",
        padding: "sm",
        alignItems: "center",
        justifyContent: "center",
        width: "fit",
        background: "surface",
        color: "foreground",
        borderColor: "border",
        borderWidth: "thin",
        borderRadius: "md",
        shadow: "none",
        hover: { background: "mutedSurface", color: "foreground", borderColor: "accent" },
        focus: { borderColor: "focusRing", borderWidth: "medium", shadow: "sm" },
      },
    },
    badge: {
      description: "A compact neutral status container.",
      useWhen: "Use around a short status, tag, or count label.",
      style: {
        direction: "row",
        padding: "sm",
        alignItems: "center",
        width: "fit",
        background: "mutedSurface",
        color: "foreground",
        borderRadius: "full",
      },
    },
    successBadge: {
      description: "A compact positive status container.",
      useWhen: "Use around a short success or completion label.",
      style: {
        direction: "row",
        padding: "sm",
        alignItems: "center",
        width: "fit",
        background: "successSurface",
        color: "successForeground",
        borderRadius: "full",
      },
    },
    warningBadge: {
      description: "A compact caution status container.",
      useWhen: "Use around a short warning or attention label.",
      style: {
        direction: "row",
        padding: "sm",
        alignItems: "center",
        width: "fit",
        background: "warningSurface",
        color: "warningForeground",
        borderRadius: "full",
      },
    },
    dangerBadge: {
      description: "A compact critical status container.",
      useWhen: "Use around a short danger or failure label.",
      style: {
        direction: "row",
        padding: "sm",
        alignItems: "center",
        width: "fit",
        background: "dangerSurface",
        color: "dangerForeground",
        borderRadius: "full",
      },
    },
    infoAlert: {
      description: "An informational notice surface.",
      useWhen: "Use for a message that adds helpful context.",
      style: {
        gap: "sm",
        padding: "md",
        background: "infoSurface",
        color: "infoForeground",
        borderColor: "info",
        borderWidth: "thin",
        borderRadius: "md",
      },
    },
    successAlert: {
      description: "A positive outcome notice surface.",
      useWhen: "Use to confirm a completed or successful action.",
      style: {
        gap: "sm",
        padding: "md",
        background: "successSurface",
        color: "successForeground",
        borderColor: "success",
        borderWidth: "thin",
        borderRadius: "md",
      },
    },
    warningAlert: {
      description: "A caution notice surface.",
      useWhen: "Use for a recoverable warning that needs attention.",
      style: {
        gap: "sm",
        padding: "md",
        background: "warningSurface",
        color: "warningForeground",
        borderColor: "warning",
        borderWidth: "thin",
        borderRadius: "md",
      },
    },
    dangerAlert: {
      description: "A critical outcome notice surface.",
      useWhen: "Use for an error, failure, or destructive warning.",
      style: {
        gap: "sm",
        padding: "md",
        background: "dangerSurface",
        color: "dangerForeground",
        borderColor: "danger",
        borderWidth: "thin",
        borderRadius: "md",
      },
    },
    rail: {
      description: "A quiet side navigation rail surface.",
      useWhen: "Use for a sidebar or side-navigation column beside the main content.",
      avoidWhen: "Avoid for primary content, a horizontal toolbar, or a pressable action.",
      style: {
        gap: "sm",
        padding: "md",
        background: "mutedSurface",
        borderColor: "border",
        borderWidth: "thin",
        borderRadius: "md",
      },
    },
  },
  text: {
    heading: {
      description: "A strong section-level heading.",
      useWhen: "Use for the main heading of a compact content region.",
      style: {
        fontSize: "2xl",
        fontWeight: "bold",
        color: "foreground",
        letterSpacing: "tight",
        lineHeight: "tight",
      },
    },
    subheading: {
      description: "A lower-level heading with clear hierarchy.",
      useWhen: "Use below a section heading or above a small content group.",
      style: { fontSize: "lg", fontWeight: "semibold", color: "foreground", lineHeight: "tight" },
    },
    body: {
      description: "Standard readable body copy.",
      useWhen: "Use for ordinary explanatory text.",
      style: { fontSize: "md", fontWeight: "regular", color: "foreground", lineHeight: "normal" },
    },
    muted: {
      description: "Secondary supporting text.",
      useWhen: "Use for helper copy, captions, and less important context.",
      style: { fontSize: "sm", fontWeight: "regular", color: "mutedForeground" },
    },
    eyebrow: {
      description: "A compact label above a heading.",
      useWhen: "Use for a short category or section cue.",
      style: {
        fontSize: "xs",
        fontWeight: "bold",
        color: "accent",
        letterSpacing: "wide",
      },
    },
    metric: {
      description: "A prominent numeric or short KPI value.",
      useWhen: "Use for the primary value in a metric display.",
      style: {
        fontSize: "3xl",
        fontWeight: "bold",
        color: "foreground",
        letterSpacing: "tight",
        lineHeight: "tight",
      },
    },
    actionLabel: {
      description: "A concise label inside a pressable action Box.",
      useWhen: "Use for primary or secondary action text.",
      style: { fontSize: "sm", fontWeight: "semibold", color: "inherit", lineHeight: "tight" },
    },
    badge: {
      description: "A compact neutral badge label.",
      useWhen: "Use inside a Box using the badge Preset.",
      style: { fontSize: "xs", fontWeight: "semibold", color: "foreground", lineHeight: "tight" },
    },
    successBadge: {
      description: "A compact positive badge label.",
      useWhen: "Use inside a Box using the successBadge Preset.",
      style: {
        fontSize: "xs",
        fontWeight: "semibold",
        color: "successForeground",
        lineHeight: "tight",
      },
    },
    warningBadge: {
      description: "A compact caution badge label.",
      useWhen: "Use inside a Box using the warningBadge Preset.",
      style: {
        fontSize: "xs",
        fontWeight: "semibold",
        color: "warningForeground",
        lineHeight: "tight",
      },
    },
    dangerBadge: {
      description: "A compact critical badge label.",
      useWhen: "Use inside a Box using the dangerBadge Preset.",
      style: {
        fontSize: "xs",
        fontWeight: "semibold",
        color: "dangerForeground",
        lineHeight: "tight",
      },
    },
    infoAlert: {
      description: "Text emphasized for an informational notice.",
      useWhen: "Use for a title or key sentence inside an infoAlert Box.",
      style: { fontWeight: "semibold", color: "infoForeground" },
    },
    successAlert: {
      description: "Text emphasized for a positive notice.",
      useWhen: "Use for a title or key sentence inside a successAlert Box.",
      style: { fontWeight: "semibold", color: "successForeground" },
    },
    warningAlert: {
      description: "Text emphasized for a caution notice.",
      useWhen: "Use for a title or key sentence inside a warningAlert Box.",
      style: { fontWeight: "semibold", color: "warningForeground" },
    },
    dangerAlert: {
      description: "Text emphasized for a critical notice.",
      useWhen: "Use for a title or key sentence inside a dangerAlert Box.",
      style: { fontWeight: "semibold", color: "dangerForeground" },
    },
  },
  media: {
    hero: {
      description: "A wide prominent media treatment.",
      useWhen: "Use for a lead image or product visual.",
      style: { width: "full", aspectRatio: "wide", objectFit: "cover", borderRadius: "lg" },
    },
    thumbnail: {
      description: "A compact square media treatment.",
      useWhen: "Use for a supporting avatar-like or preview image.",
      style: { width: "full", aspectRatio: "square", objectFit: "cover", borderRadius: "md" },
    },
  },
  input: {
    standard: {
      description: "The standard full-width labeled control.",
      useWhen: "Use for ordinary form fields.",
      style: { width: "full", gap: "xs" },
    },
    compact: {
      description: "A denser control treatment.",
      useWhen: "Use in compact filters and space-constrained forms.",
      style: { width: "full", gap: "xs", control: { padding: "xs", controlHeight: "sm" } },
    },
  },
  richtext: {
    prose: {
      description: "Comfortable long-form prose typography.",
      useWhen: "Use for articles, explanations, and documentation blocks.",
      style: { fontSize: "md", color: "foreground", lineHeight: "relaxed", blockGap: "md" },
    },
    compact: {
      description: "A compact structured-text treatment.",
      useWhen: "Use for dense supporting prose with multiple blocks.",
      style: { fontSize: "sm", lineHeight: "normal", blockGap: "sm" },
    },
  },
  table: {
    standard: {
      description: "A readable bordered data table.",
      useWhen: "Use for ordinary comparable records.",
      style: { width: "full", background: "surface", borderRadius: "md", shadow: "none" },
    },
    compact: {
      description: "A denser table treatment.",
      useWhen: "Use when many short records must fit in limited space.",
      style: { cell: { fontSize: "xs", padding: "xs" }, header: { fontSize: "xs", padding: "xs" } },
    },
  },
  chart: {
    panel: {
      description: "A self-contained chart surface.",
      useWhen: "Use when a chart should read as a distinct dashboard panel.",
      style: { padding: "md", background: "surface", borderRadius: "md", shadow: "sm" },
    },
  },
  list: {
    standard: {
      description: "A comfortably spaced list of surfaced items.",
      useWhen: "Use for ordinary titled or descriptive records.",
      style: { gap: "sm", item: { gap: "xs", padding: "sm", borderRadius: "md" } },
    },
    compact: {
      description: "A dense list of short items.",
      useWhen: "Use for concise records in limited vertical space.",
      style: {
        gap: "xs",
        item: { gap: "xs", padding: "xs", borderRadius: "sm" },
        body: { fontSize: "xs" },
      },
    },
  },
  keyValue: {
    standard: {
      description: "A balanced label-and-value summary.",
      useWhen: "Use for metadata, properties, and compact facts.",
      style: { gap: "sm", padding: "md", background: "surface", borderRadius: "md" },
    },
  },
  progress: {
    standard: {
      description: "The standard accent progress treatment.",
      useWhen: "Use for neutral ongoing completion.",
      style: { width: "full", gap: "xs", fill: { background: "accent" } },
    },
    success: {
      description: "A progress treatment indicating successful completion.",
      useWhen: "Use when progress represents a positive completed outcome.",
      style: { width: "full", label: { color: "success" }, fill: { background: "success" } },
    },
  },
  loading: {
    standard: {
      description: "The standard inline loading treatment.",
      useWhen: "Use while a nearby result or action is pending.",
      style: {
        direction: "row",
        gap: "sm",
        alignItems: "center",
        indicator: { animation: "pulse" },
        label: { fontWeight: "medium" },
      },
    },
    subdued: {
      description: "A low-emphasis loading treatment.",
      useWhen: "Use for background refreshes that should not dominate the page.",
      style: {
        gap: "xs",
        indicator: { size: "sm", color: "mutedForeground", animation: "pulse" },
        label: { fontSize: "xs", color: "mutedForeground" },
      },
    },
  },
} satisfies FacetPresets;
