export const SHIPPED_SERVICE_SURFACE_COMPONENTS = Object.freeze([
  "Screen",
  "Stack",
  "Row",
  "Grid",
  "Split",
  "AppShell",
  "Section",
  "Card",
  "Modal",
  "Divider",
  "Navigation",
  "NavigationItem",
  "Button",
  "ActionGroup",
  "ActionBar",
  "Text",
  "Avatar",
  "Icon",
  "Image",
  "Badge",
  "Metric",
  "MetricGroup",
  "Table",
  "Chart",
  "Progress",
  "Timeline",
  "List",
  "Header",
  "Collection",
  "ItemCard",
  "Detail",
  "PropertyList",
  "Property",
  "Board",
  "BoardColumn",
  "Calendar",
  "Result",
  "Empty",
  "Alert",
  "Form",
  "Field",
  "Select",
  "ChoiceGroup",
  "Toggle",
  "MessageThread",
  "Accordion",
  "AccordionItem",
] as const);

export const DEFERRED_SERVICE_SURFACE_COMPONENTS = Object.freeze([] as const);

export type ShippedServiceSurfaceComponent = (typeof SHIPPED_SERVICE_SURFACE_COMPONENTS)[number];
export type DeferredServiceSurfaceComponent = (typeof DEFERRED_SERVICE_SURFACE_COMPONENTS)[number];
export type ServiceSurfaceGroupId =
  | "landing"
  | "personal-profile-resume"
  | "commerce"
  | "saas"
  | "analytics"
  | "booking-consultation"
  | "support"
  | "onboarding"
  | "operations-board"
  | "calendar-scheduling"
  | "messaging"
  | "form-result";

export interface ServiceSurfaceGroup {
  readonly id: ServiceSurfaceGroupId;
  readonly label: string;
  readonly description: string;
  readonly dashboardLike: boolean;
  readonly shippedComponents: readonly ShippedServiceSurfaceComponent[];
  readonly deferredComponents: readonly DeferredServiceSurfaceComponent[];
}

function group(
  id: ServiceSurfaceGroupId,
  label: string,
  description: string,
  dashboardLike: boolean,
  shippedComponents: readonly ShippedServiceSurfaceComponent[],
): ServiceSurfaceGroup {
  return Object.freeze({
    id,
    label,
    description,
    dashboardLike,
    shippedComponents: Object.freeze(shippedComponents),
    deferredComponents: DEFERRED_SERVICE_SURFACE_COMPONENTS,
  });
}

export const SERVICE_SURFACE_GROUPS: readonly ServiceSurfaceGroup[] = Object.freeze([
  group(
    "landing",
    "Landing",
    "Product, campaign, event, waitlist, and service landing surfaces.",
    false,
    [
      "Screen",
      "Navigation",
      "NavigationItem",
      "Header",
      "Section",
      "Stack",
      "Row",
      "Grid",
      "ItemCard",
      "Image",
      "Badge",
      "Text",
      "ActionBar",
      "Button",
    ],
  ),
  group(
    "personal-profile-resume",
    "Personal Profile / Resume",
    "Profiles, resumes, portfolios, biographies, and personal proof surfaces.",
    false,
    [
      "Screen",
      "Header",
      "Avatar",
      "Detail",
      "PropertyList",
      "Property",
      "Timeline",
      "Collection",
      "ItemCard",
      "ActionGroup",
      "Button",
    ],
  ),
  group(
    "commerce",
    "Commerce",
    "Product discovery, detail, order status, and purchase-support surfaces.",
    false,
    [
      "Screen",
      "Header",
      "Collection",
      "ItemCard",
      "Detail",
      "Image",
      "PropertyList",
      "Property",
      "Badge",
      "ActionBar",
      "Button",
    ],
  ),
  group(
    "saas",
    "SaaS",
    "Workspace, account, settings, approval, and product administration surfaces.",
    true,
    [
      "Screen",
      "AppShell",
      "Navigation",
      "NavigationItem",
      "Header",
      "MetricGroup",
      "Metric",
      "Table",
      "Form",
      "Toggle",
      "Button",
    ],
  ),
  group(
    "analytics",
    "Analytics",
    "Metric summaries, trends, tables, findings, and operating readouts.",
    true,
    [
      "Screen",
      "Header",
      "MetricGroup",
      "Metric",
      "Chart",
      "Table",
      "Progress",
      "Alert",
      "Section",
      "Grid",
    ],
  ),
  group(
    "booking-consultation",
    "Booking / Consultation",
    "Service selection, appointment requests, consultation intake, and confirmation.",
    false,
    [
      "Screen",
      "Header",
      "Detail",
      "Calendar",
      "Form",
      "Field",
      "Select",
      "ChoiceGroup",
      "ActionBar",
      "Button",
      "Result",
    ],
  ),
  group(
    "support",
    "Support",
    "Help centers, ticket context, troubleshooting, and escalation surfaces.",
    false,
    [
      "Screen",
      "Header",
      "Alert",
      "Accordion",
      "AccordionItem",
      "MessageThread",
      "Form",
      "Field",
      "Select",
      "Button",
    ],
  ),
  group(
    "onboarding",
    "Onboarding",
    "Guided setup, preference collection, progress, and next-step surfaces.",
    false,
    [
      "Screen",
      "Header",
      "Progress",
      "List",
      "Form",
      "Field",
      "Select",
      "ChoiceGroup",
      "Toggle",
      "ActionBar",
      "Button",
    ],
  ),
  group(
    "operations-board",
    "Operations / Board",
    "Workflow boards, queues, handoffs, and bounded operational records.",
    true,
    [
      "Screen",
      "AppShell",
      "Navigation",
      "NavigationItem",
      "Header",
      "Board",
      "BoardColumn",
      "Card",
      "Badge",
      "ActionBar",
      "Button",
    ],
  ),
  group(
    "calendar-scheduling",
    "Calendar / Scheduling",
    "Agenda, availability, event selection, and schedule management surfaces.",
    false,
    [
      "Screen",
      "Header",
      "Calendar",
      "Collection",
      "ItemCard",
      "Form",
      "Select",
      "ActionBar",
      "Button",
    ],
  ),
  group(
    "messaging",
    "Messaging",
    "Conversation history, contact context, replies, and escalation actions.",
    false,
    [
      "Screen",
      "Header",
      "MessageThread",
      "Form",
      "Field",
      "ActionGroup",
      "Button",
      "Alert",
      "Icon",
    ],
  ),
  group(
    "form-result",
    "Form / Result",
    "Input-heavy workflows that resolve into a clear success, warning, or empty state.",
    false,
    [
      "Screen",
      "Split",
      "Modal",
      "Divider",
      "Form",
      "Field",
      "Select",
      "ChoiceGroup",
      "Toggle",
      "Result",
      "Empty",
      "ActionBar",
      "Button",
    ],
  ),
]);
