export const SHIPPED_SERVICE_SURFACE_COMPONENTS = Object.freeze([
  "Screen",
  "AppShell",
  "Stack",
  "Row",
  "Split",
  "Grid",
  "Modal",
  "Card",
  "Empty",
  "LogoMark",
  "Nav",
  "SideNav",
  "SideNavItem",
  "Section",
  "Divider",
  "Hero",
  "Avatar",
  "ProfileHeader",
  "ProductShowcase",
  "VisualPanel",
  "MediaCard",
  "LinkList",
  "SocialLinks",
  "FeatureList",
  "StatStrip",
  "Gallery",
  "Testimonial",
  "Timeline",
  "CTA",
  "Alert",
  "Progress",
  "Footer",
  "Text",
  "Metric",
  "Badge",
  "Table",
  "Button",
  "Field",
] as const);

export const DEFERRED_SERVICE_SURFACE_COMPONENTS = Object.freeze([
  "Image",
  "Logo",
  "Pricing",
  "Form",
] as const);

export type ShippedServiceSurfaceComponent = (typeof SHIPPED_SERVICE_SURFACE_COMPONENTS)[number];
export type DeferredServiceSurfaceComponent = (typeof DEFERRED_SERVICE_SURFACE_COMPONENTS)[number];
export type ServiceSurfaceGroupId =
  | "personal-presence"
  | "marketing-landing"
  | "commerce-booking"
  | "saas-workspace"
  | "content-editorial"
  | "data-report"
  | "support-form-flow";

export interface ServiceSurfaceGroup {
  readonly id: ServiceSurfaceGroupId;
  readonly label: string;
  readonly description: string;
  readonly dashboardLike: boolean;
  readonly shippedComponents: readonly ShippedServiceSurfaceComponent[];
  readonly deferredComponents: readonly DeferredServiceSurfaceComponent[];
}

export const SERVICE_SURFACE_GROUPS: readonly ServiceSurfaceGroup[] = Object.freeze([
  {
    id: "personal-presence",
    label: "Personal Presence",
    description: "Personal bio, link-in-bio, resume, portfolio, and creator profile surfaces.",
    dashboardLike: false,
    shippedComponents: [
      "Screen",
      "LogoMark",
      "Nav",
      "Hero",
      "Avatar",
      "ProfileHeader",
      "SocialLinks",
      "MediaCard",
      "LinkList",
      "Gallery",
      "Timeline",
      "Footer",
      "Section",
      "Stack",
      "Row",
      "Split",
      "Grid",
      "Card",
      "CTA",
      "Testimonial",
      "Badge",
      "Button",
      "Text",
    ],
    deferredComponents: ["Image"],
  },
  {
    id: "marketing-landing",
    label: "Marketing / Landing",
    description: "Product landing, campaign, event, waitlist, and newsletter signup surfaces.",
    dashboardLike: false,
    shippedComponents: [
      "Screen",
      "LogoMark",
      "Nav",
      "Hero",
      "ProductShowcase",
      "MediaCard",
      "VisualPanel",
      "CTA",
      "FeatureList",
      "StatStrip",
      "Gallery",
      "Timeline",
      "Testimonial",
      "Footer",
      "Section",
      "Stack",
      "Row",
      "Split",
      "Grid",
      "Card",
      "Badge",
      "Button",
      "Text",
    ],
    deferredComponents: ["Image", "Logo", "Pricing"],
  },
  {
    id: "commerce-booking",
    label: "Commerce / Booking",
    description:
      "Small-business product, service menu, booking, inquiry, and order-status surfaces.",
    dashboardLike: false,
    shippedComponents: [
      "Screen",
      "LogoMark",
      "Nav",
      "Hero",
      "ProductShowcase",
      "MediaCard",
      "Gallery",
      "StatStrip",
      "Section",
      "Stack",
      "Split",
      "Grid",
      "FeatureList",
      "Card",
      "Field",
      "Button",
      "Alert",
      "Badge",
      "Text",
    ],
    deferredComponents: ["Image", "Logo", "Form", "Pricing"],
  },
  {
    id: "saas-workspace",
    label: "SaaS / Workspace",
    description: "Dashboard, settings, account management, operations, approval, and review flows.",
    dashboardLike: true,
    shippedComponents: [
      "Screen",
      "AppShell",
      "Nav",
      "SideNav",
      "SideNavItem",
      "Hero",
      "Stack",
      "Row",
      "Split",
      "Grid",
      "Section",
      "Card",
      "Text",
      "Metric",
      "Table",
      "Badge",
      "Button",
      "Field",
      "Modal",
      "Alert",
      "Progress",
      "Footer",
    ],
    deferredComponents: [],
  },
  {
    id: "content-editorial",
    label: "Content / Editorial",
    description: "Articles, guides, reports, case studies, release notes, and story-led pages.",
    dashboardLike: false,
    shippedComponents: [
      "Screen",
      "LogoMark",
      "Nav",
      "Hero",
      "ProductShowcase",
      "MediaCard",
      "VisualPanel",
      "Section",
      "Stack",
      "Row",
      "Grid",
      "Card",
      "Divider",
      "Gallery",
      "Timeline",
      "Testimonial",
      "CTA",
      "Footer",
      "Text",
      "LinkList",
      "Badge",
      "Button",
    ],
    deferredComponents: ["Image"],
  },
  {
    id: "data-report",
    label: "Data / Report",
    description:
      "Metric summaries, tables, status reports, analysis results, and operating reviews.",
    dashboardLike: false,
    shippedComponents: [
      "Screen",
      "AppShell",
      "Nav",
      "SideNav",
      "SideNavItem",
      "Hero",
      "StatStrip",
      "VisualPanel",
      "Stack",
      "Section",
      "Split",
      "Grid",
      "Card",
      "Metric",
      "Table",
      "Badge",
      "Progress",
      "Alert",
      "Footer",
    ],
    deferredComponents: [],
  },
  {
    id: "support-form-flow",
    label: "Support / Form Flow",
    description: "Contact intake, application, onboarding, survey, ticket, and consultation flows.",
    dashboardLike: false,
    shippedComponents: [
      "Screen",
      "LogoMark",
      "Nav",
      "Hero",
      "ProfileHeader",
      "SocialLinks",
      "MediaCard",
      "Gallery",
      "Timeline",
      "Section",
      "Split",
      "Field",
      "Button",
      "Alert",
      "Progress",
      "Card",
      "Modal",
      "Stack",
      "Row",
      "Text",
      "Footer",
    ],
    deferredComponents: ["Form"],
  },
]);
