import type { FacetTree } from "@facet/core";
import { QUICKSTART_NAV_ITEMS } from "./guide-shared.js";

const NAV_ITEM_STYLE = {
  preset: "secondaryAction",
  active: { preset: "primaryAction" },
} as const;
const NAV_LABEL_STYLE = {
  preset: "actionLabel",
  active: { color: "accentForeground" },
} as const;

export const QUICKSTART_SYSTEM_NODES = {
  "qs.system.root": {
    id: "qs.system.root",
    type: "box",
    style: { direction: "column", gap: "lg", padding: "xl" },
    children: [
      "qs.nav.system",
      "qs.system.hero",
      "qs.system.theme",
      "qs.system.bricks",
      "qs.system.patterns",
      "qs.system.discovery",
    ],
  },
  "qs.nav.system": {
    id: "qs.nav.system",
    type: "box",
    style: { direction: "row", gap: "xs", wrap: true, width: "full" },
    children: [
      "qs.nav.system.what",
      "qs.nav.system.structure",
      "qs.nav.system.system",
      "qs.nav.system.usecases",
    ],
  },
  "qs.nav.system.what": {
    id: "qs.nav.system.what",
    type: "box",
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[0].to },
    style: NAV_ITEM_STYLE,
    children: ["qs.nav.system.what.label"],
    onPress: { kind: "navigate", to: QUICKSTART_NAV_ITEMS[0].to },
  },
  "qs.nav.system.what.label": {
    id: "qs.nav.system.what.label",
    type: "text",
    value: QUICKSTART_NAV_ITEMS[0].label,
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[0].to },
    style: NAV_LABEL_STYLE,
  },
  "qs.nav.system.structure": {
    id: "qs.nav.system.structure",
    type: "box",
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[1].to },
    style: NAV_ITEM_STYLE,
    children: ["qs.nav.system.structure.label"],
    onPress: { kind: "navigate", to: QUICKSTART_NAV_ITEMS[1].to },
  },
  "qs.nav.system.structure.label": {
    id: "qs.nav.system.structure.label",
    type: "text",
    value: QUICKSTART_NAV_ITEMS[1].label,
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[1].to },
    style: NAV_LABEL_STYLE,
  },
  "qs.nav.system.system": {
    id: "qs.nav.system.system",
    type: "box",
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[2].to },
    style: NAV_ITEM_STYLE,
    children: ["qs.nav.system.system.label"],
    onPress: { kind: "navigate", to: QUICKSTART_NAV_ITEMS[2].to },
  },
  "qs.nav.system.system.label": {
    id: "qs.nav.system.system.label",
    type: "text",
    value: QUICKSTART_NAV_ITEMS[2].label,
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[2].to },
    style: NAV_LABEL_STYLE,
  },
  "qs.nav.system.usecases": {
    id: "qs.nav.system.usecases",
    type: "box",
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[3].to },
    style: NAV_ITEM_STYLE,
    children: ["qs.nav.system.usecases.label"],
    onPress: { kind: "navigate", to: QUICKSTART_NAV_ITEMS[3].to },
  },
  "qs.nav.system.usecases.label": {
    id: "qs.nav.system.usecases.label",
    type: "text",
    value: QUICKSTART_NAV_ITEMS[3].label,
    activeWhen: { screen: QUICKSTART_NAV_ITEMS[3].to },
    style: NAV_LABEL_STYLE,
  },
  "qs.system.hero": {
    id: "qs.system.hero",
    type: "box",
    style: {
      preset: "panel",
      padding: "lg",
      borderWidth: "none",
      borderRadius: "lg",
      shadow: "none",
      width: "full",
    },
    children: [
      "qs.system.hero.eyebrow",
      "qs.system.hero.title",
      "qs.system.hero.body",
      "qs.system.hero.alert",
    ],
  },
  "qs.system.hero.eyebrow": {
    id: "qs.system.hero.eyebrow",
    type: "text",
    value: "Default assets",
    style: { preset: "eyebrow" },
  },
  "qs.system.hero.title": {
    id: "qs.system.hero.title",
    type: "text",
    value: "Design System",
    style: { preset: "heading" },
  },
  "qs.system.hero.body": {
    id: "qs.system.hero.body",
    type: "text",
    value:
      "The agent starts with a Pattern when one fits, then authors native Bricks using Theme Presets and deliberate direct style.",
    style: { preset: "body" },
  },
  "qs.system.hero.alert": {
    id: "qs.system.hero.alert",
    type: "box",
    style: { preset: "infoAlert" },
    children: ["qs.system.hero.alert.title", "qs.system.hero.alert.body"],
  },
  "qs.system.hero.alert.title": {
    id: "qs.system.hero.alert.title",
    type: "text",
    value: "Renderer QA surface",
    style: { preset: "infoAlert" },
  },
  "qs.system.hero.alert.body": {
    id: "qs.system.hero.alert.body",
    type: "text",
    value:
      "This tab also exercises alignment, overflow, native controls, Brick targets, Presets, and direct style.",
    style: { preset: "body", color: "infoForeground" },
  },
  "qs.system.theme": {
    id: "qs.system.theme",
    type: "box",
    style: {
      preset: "panel",
      padding: "lg",
      borderWidth: "none",
      borderRadius: "lg",
      shadow: "none",
      width: "full",
    },
    children: [
      "qs.system.theme.title",
      "qs.system.theme.body",
      "qs.system.theme.badges",
      "qs.system.theme.progress",
      "qs.system.theme.list",
    ],
  },
  "qs.system.theme.title": {
    id: "qs.system.theme.title",
    type: "text",
    value: "Theme, Presets, and token names",
    style: { preset: "heading" },
  },
  "qs.system.theme.body": {
    id: "qs.system.theme.body",
    type: "text",
    value:
      "A Theme defines concrete values and Brick defaults. Agents usually choose a same-Brick Preset, then add direct style only where the Pattern needs it.",
    style: { preset: "body" },
  },
  "qs.system.theme.badges": {
    id: "qs.system.theme.badges",
    type: "box",
    style: { direction: "row", gap: "sm", wrap: true },
    children: [
      "qs.system.badge.neutral",
      "qs.system.badge.success",
      "qs.system.badge.warning",
      "qs.system.badge.danger",
    ],
  },
  "qs.system.badge.neutral": {
    id: "qs.system.badge.neutral",
    type: "box",
    style: { preset: "badge" },
    children: ["qs.system.badge.neutral.label"],
  },
  "qs.system.badge.neutral.label": {
    id: "qs.system.badge.neutral.label",
    type: "text",
    value: "neutral",
    style: { preset: "badge" },
  },
  "qs.system.badge.success": {
    id: "qs.system.badge.success",
    type: "box",
    style: { preset: "successBadge" },
    children: ["qs.system.badge.success.label"],
  },
  "qs.system.badge.success.label": {
    id: "qs.system.badge.success.label",
    type: "text",
    value: "success",
    style: { preset: "successBadge" },
  },
  "qs.system.badge.warning": {
    id: "qs.system.badge.warning",
    type: "box",
    style: { preset: "warningBadge" },
    children: ["qs.system.badge.warning.label"],
  },
  "qs.system.badge.warning.label": {
    id: "qs.system.badge.warning.label",
    type: "text",
    value: "warning",
    style: { preset: "warningBadge" },
  },
  "qs.system.badge.danger": {
    id: "qs.system.badge.danger",
    type: "box",
    style: { preset: "dangerBadge" },
    children: ["qs.system.badge.danger.label"],
  },
  "qs.system.badge.danger.label": {
    id: "qs.system.badge.danger.label",
    type: "text",
    value: "danger",
    style: { preset: "dangerBadge" },
  },
  "qs.system.theme.progress": {
    id: "qs.system.theme.progress",
    type: "progress",
    label: "Preset coverage",
    value: 92,
    style: { preset: "success" },
  },
  "qs.system.theme.list": {
    id: "qs.system.theme.list",
    type: "list",
    style: { preset: "compact" },
    items: [
      { title: "Theme", body: "Concrete CSS values stay inside assets and the renderer." },
      { title: "Presets", body: "Named single-Brick styles carry use guidance." },
      { title: "Direct style", body: "Closed property and token names handle specific needs." },
    ],
  },
  "qs.system.bricks": {
    id: "qs.system.bricks",
    type: "box",
    style: {
      preset: "panel",
      padding: "lg",
      borderWidth: "none",
      borderRadius: "lg",
      shadow: "none",
      width: "full",
    },
    children: [
      "qs.system.bricks.title",
      "qs.system.bricks.body",
      "qs.system.actions.card",
      "qs.system.data.card",
      "qs.system.form.card",
      "qs.system.feedback.card",
    ],
  },
  "qs.system.bricks.title": {
    id: "qs.system.bricks.title",
    type: "text",
    value: "Brick gallery",
    style: { preset: "heading" },
  },
  "qs.system.bricks.body": {
    id: "qs.system.bricks.body",
    type: "text",
    value:
      "All eleven native Bricks own a closed style vocabulary. Each supported target and token choice is defined by Core.",
    style: { preset: "body" },
  },
  "qs.system.actions.card": {
    id: "qs.system.actions.card",
    type: "box",
    style: { preset: "panel", gap: "sm" },
    children: [
      "qs.system.actions.card.title",
      "qs.system.actions.card.body",
      "qs.system.action.buttons",
      "qs.system.action.metric",
      "qs.system.action.progress",
      "qs.system.action.divider",
    ],
  },
  "qs.system.actions.card.title": {
    id: "qs.system.actions.card.title",
    type: "text",
    value: "Actions and layout",
    style: { preset: "subheading" },
  },
  "qs.system.actions.card.body": {
    id: "qs.system.actions.card.body",
    type: "text",
    value:
      "Pressable boxes, bordered panels, label/value summaries, badges, progress, dividers, and flow boxes.",
    style: { preset: "muted" },
  },
  "qs.system.action.buttons": {
    id: "qs.system.action.buttons",
    type: "box",
    style: { direction: "row", gap: "sm", wrap: true },
    children: ["qs.system.button.primary", "qs.system.button.secondary", "qs.system.button.danger"],
  },
  "qs.system.button.primary": {
    id: "qs.system.button.primary",
    type: "box",
    style: { preset: "primaryAction" },
    children: ["qs.system.button.primary.label"],
    onPress: { kind: "agent", name: "show_primary_action" },
  },
  "qs.system.button.primary.label": {
    id: "qs.system.button.primary.label",
    type: "text",
    value: "Primary",
    style: { preset: "actionLabel" },
  },
  "qs.system.button.secondary": {
    id: "qs.system.button.secondary",
    type: "box",
    style: { preset: "secondaryAction" },
    children: ["qs.system.button.secondary.label"],
    onPress: { kind: "agent", name: "show_secondary_action" },
  },
  "qs.system.button.secondary.label": {
    id: "qs.system.button.secondary.label",
    type: "text",
    value: "Secondary",
    style: { preset: "actionLabel" },
  },
  "qs.system.button.danger": {
    id: "qs.system.button.danger",
    type: "box",
    style: {
      direction: "row",
      padding: "sm",
      justifyContent: "center",
      background: "danger",
      borderColor: "danger",
      borderWidth: "thin",
      borderRadius: "md",
    },
    children: ["qs.system.button.danger.label"],
    onPress: { kind: "agent", name: "show_danger_action" },
  },
  "qs.system.button.danger.label": {
    id: "qs.system.button.danger.label",
    type: "text",
    value: "Danger",
    style: { preset: "actionLabel", color: "dangerForeground" },
  },
  "qs.system.action.metric": {
    id: "qs.system.action.metric",
    type: "box",
    style: { preset: "panel", gap: "xs", shadow: "none" },
    children: ["qs.system.action.metric.label", "qs.system.action.metric.value"],
  },
  "qs.system.action.metric.label": {
    id: "qs.system.action.metric.label",
    type: "text",
    value: "Interactive bricks",
    style: { preset: "muted", fontWeight: "medium" },
  },
  "qs.system.action.metric.value": {
    id: "qs.system.action.metric.value",
    type: "text",
    value: "11 closed Bricks",
    style: { preset: "metric", color: "success" },
  },
  "qs.system.action.progress": {
    id: "qs.system.action.progress",
    type: "progress",
    label: "Polish pass",
    value: 76,
    style: { preset: "standard", label: { color: "info" } },
  },
  "qs.system.action.divider": {
    id: "qs.system.action.divider",
    type: "box",
    style: { borderWidth: "thin", background: "mutedSurface", borderRadius: "full" },
    children: [],
  },
  "qs.system.data.card": {
    id: "qs.system.data.card",
    type: "box",
    style: { preset: "panel", gap: "sm" },
    children: [
      "qs.system.data.card.title",
      "qs.system.data.card.body",
      "qs.system.data.chart",
      "qs.system.data.table",
    ],
  },
  "qs.system.data.card.title": {
    id: "qs.system.data.card.title",
    type: "text",
    value: "Display-only data",
    style: { preset: "subheading" },
  },
  "qs.system.data.card.body": {
    id: "qs.system.data.card.body",
    type: "text",
    value:
      "Tables and charts show bounded data only. They do not fetch, sort, or bind backend state.",
    style: { preset: "muted" },
  },
  "qs.system.data.chart": {
    id: "qs.system.data.chart",
    type: "chart",
    title: "Renderer checks",
    kind: "bar",
    style: { preset: "panel" },
    labels: ["Table", "Chart", "Field", "Reference"],
    series: [{ label: "coverage", values: [3, 4, 3, 5] }],
  },
  "qs.system.data.table": {
    id: "qs.system.data.table",
    type: "table",
    caption: "Brick style ownership",
    style: { preset: "standard" },
    columns: [
      { key: "brick", label: "Brick" },
      { key: "contract", label: "Owned role" },
    ],
    rows: [
      { brick: "box", contract: "container or pressable action" },
      { brick: "table", contract: "display-only rows" },
      { brick: "progress", contract: "track and fill" },
      { brick: "input", contract: "browser view-state" },
    ],
  },
  "qs.system.form.card": {
    id: "qs.system.form.card",
    type: "box",
    style: { preset: "panel", gap: "sm" },
    children: [
      "qs.system.form.card.title",
      "qs.system.form.card.body",
      "qs.system.form.name",
      "qs.system.form.kind",
      "qs.system.form.submit",
    ],
  },
  "qs.system.form.card.title": {
    id: "qs.system.form.card.title",
    type: "text",
    value: "Field controls",
    style: { preset: "subheading" },
  },
  "qs.system.form.card.body": {
    id: "qs.system.form.card.body",
    type: "text",
    value: "Field values stay in browser view-state until an action collects them.",
    style: { preset: "muted" },
  },
  "qs.system.form.name": {
    id: "qs.system.form.name",
    type: "input",
    name: "showcase_name",
    label: "Showcase name",
    placeholder: "Design audit",
    style: { preset: "standard" },
  },
  "qs.system.form.kind": {
    id: "qs.system.form.kind",
    type: "input",
    name: "showcase_kind",
    input: "select",
    label: "Surface type",
    options: ["Dashboard", "Form", "Pattern", "Workflow"],
    style: { preset: "standard" },
  },
  "qs.system.form.submit": {
    id: "qs.system.form.submit",
    type: "box",
    style: { preset: "secondaryAction" },
    children: ["qs.system.form.submit.label"],
    onPress: { kind: "agent", name: "inspect_showcase_fields", collect: "qs.system.form.card" },
  },
  "qs.system.form.submit.label": {
    id: "qs.system.form.submit.label",
    type: "text",
    value: "Collect field values",
    style: { preset: "actionLabel" },
  },
  "qs.system.feedback.card": {
    id: "qs.system.feedback.card",
    type: "box",
    style: { preset: "panel", gap: "sm" },
    children: [
      "qs.system.feedback.card.title",
      "qs.system.feedback.card.body",
      "qs.system.feedback.alert",
      "qs.system.feedback.list",
    ],
  },
  "qs.system.feedback.card.title": {
    id: "qs.system.feedback.card.title",
    type: "text",
    value: "Feedback surfaces",
    style: { preset: "subheading" },
  },
  "qs.system.feedback.card.body": {
    id: "qs.system.feedback.card.body",
    type: "text",
    value:
      "Alerts and lists carry product state without overlays, z-index, or absolute positioning.",
    style: { preset: "muted" },
  },
  "qs.system.feedback.alert": {
    id: "qs.system.feedback.alert",
    type: "box",
    style: { preset: "successAlert" },
    children: ["qs.system.feedback.alert.title", "qs.system.feedback.alert.body"],
  },
  "qs.system.feedback.alert.title": {
    id: "qs.system.feedback.alert.title",
    type: "text",
    value: "Token-only styling",
    style: { preset: "successAlert" },
  },
  "qs.system.feedback.alert.body": {
    id: "qs.system.feedback.alert.body",
    type: "text",
    value: "The agent never chooses raw colors, classes, pixels, HTML, or scripts.",
    style: { preset: "body", color: "successForeground" },
  },
  "qs.system.feedback.list": {
    id: "qs.system.feedback.list",
    type: "list",
    style: { preset: "standard" },
    items: [
      { title: "Flow layout", body: "No overlay or absolute-position contracts." },
      { title: "Bounded intent", body: "Each Brick exposes only its owned style vocabulary." },
      { title: "Fail-safe renderer", body: "Malformed nodes skip instead of throwing." },
    ],
  },
  "qs.system.patterns": {
    id: "qs.system.patterns",
    type: "box",
    style: {
      preset: "panel",
      padding: "lg",
      borderWidth: "none",
      borderRadius: "lg",
      shadow: "none",
      width: "full",
    },
    children: [
      "qs.system.patterns.title",
      "qs.system.patterns.body",
      "qs.system.patterns.list",
      "qs.system.patterns.table",
    ],
  },
  "qs.system.patterns.title": {
    id: "qs.system.patterns.title",
    type: "text",
    value: "Patterns",
    style: { preset: "heading" },
  },
  "qs.system.patterns.body": {
    id: "qs.system.patterns.body",
    type: "text",
    value:
      "For a complex UI, the agent sees Pattern names and use guidance first, reads one when useful, then authors its own native Bricks with Presets and direct style.",
    style: { preset: "body" },
  },
  "qs.system.patterns.list": {
    id: "qs.system.patterns.list",
    type: "list",
    style: { preset: "compact" },
    items: [
      { title: "Pattern index", body: "Start from each name, description, and useWhen." },
      { title: "Optional read", body: "Inspect one concrete Pattern only when it helps." },
      {
        title: "Native authoring",
        body: "Write the final page separately with ordinary native Bricks.",
      },
    ],
  },
  "qs.system.patterns.table": {
    id: "qs.system.patterns.table",
    type: "table",
    caption: "Pattern examples",
    style: { preset: "standard" },
    columns: [
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
    ],
    rows: [
      {
        name: "hero",
        description: "A compact product hero with a title, subtitle, and CTA.",
      },
      {
        name: "dashboard-summary",
        description: "A KPI summary section with label/value rows and status.",
      },
      {
        name: "settings-panel",
        description: "A settings card with two editable fields and a save action.",
      },
    ],
  },
  "qs.system.discovery": {
    id: "qs.system.discovery",
    type: "box",
    style: {
      preset: "panel",
      padding: "lg",
      borderWidth: "none",
      borderRadius: "lg",
      shadow: "none",
      width: "full",
    },
    children: ["qs.system.discovery.title", "qs.system.discovery.body", "qs.system.discovery.list"],
  },
  "qs.system.discovery.title": {
    id: "qs.system.discovery.title",
    type: "text",
    value: "Progressive discovery",
    style: { preset: "heading" },
  },
  "qs.system.discovery.body": {
    id: "qs.system.discovery.body",
    type: "text",
    value:
      "The agent gets short indexes first and asks for the exact Pattern, Brick style specification, or same-Brick Preset only when needed.",
    style: { preset: "body" },
  },
  "qs.system.discovery.list": {
    id: "qs.system.discovery.list",
    type: "list",
    style: { preset: "standard" },
    items: [
      { title: "Pattern", body: "Name and use guidance first; concrete tree on demand." },
      { title: "Brick", body: "Owned fields, style targets, properties, and allowed names." },
      { title: "Preset", body: "Same-Brick style bundle and use guidance on demand." },
      { title: "Fallback", body: "Theme default when style is omitted." },
    ],
  },
} satisfies FacetTree["nodes"];
