import type { FacetTree } from "@facet/core";
import { QUICKSTART_NAV_ITEMS } from "./guide-shared.js";

export const QUICKSTART_SYSTEM_NODES = {
  "qs.system.root": {
    id: "qs.system.root",
    type: "box",
    style: { direction: "col", gap: "lg", pad: "xl" },
    children: [
      "qs.nav.system",
      "qs.system.hero",
      "qs.system.theme",
      "qs.system.bricks",
      "qs.system.compositions",
      "qs.system.catalog",
    ],
  },
  "qs.nav.system": {
    id: "qs.nav.system",
    type: "tabs",
    variant: "default",
    items: QUICKSTART_NAV_ITEMS,
  },
  "qs.system.hero": {
    id: "qs.system.hero",
    type: "section",
    eyebrow: "Default assets",
    title: "Design System",
    body: "The agent can introduce the default theme, catalog variants, intrinsic components, fields, and composition patterns through live Facet UI examples.",
    variant: "surface",
    children: ["qs.system.hero.alert"],
  },
  "qs.system.hero.alert": {
    id: "qs.system.hero.alert",
    type: "alert",
    title: "Renderer QA surface",
    body: "This tab doubles as a renderer QA surface for alignment, overflow, native-control, and recipe-part issues.",
    variant: "info",
    tone: "info",
  },
  "qs.system.theme": {
    id: "qs.system.theme",
    type: "section",
    title: "Theme recipes",
    body: "Agents choose variants and bounded tones. The renderer resolves token-only recipes into the final UI.",
    variant: "surface",
    children: ["qs.system.theme.badges", "qs.system.theme.progress", "qs.system.theme.list"],
  },
  "qs.system.theme.badges": {
    id: "qs.system.theme.badges",
    type: "box",
    style: { direction: "row", gap: "sm", wrap: true },
    children: [
      "qs.system.badge.neutral",
      "qs.system.badge.success",
      "qs.system.badge.warning",
      "qs.system.badge.danger",
    ],
  },
  "qs.system.badge.neutral": {
    id: "qs.system.badge.neutral",
    type: "badge",
    label: "neutral",
    variant: "neutral",
    tone: "neutral",
  },
  "qs.system.badge.success": {
    id: "qs.system.badge.success",
    type: "badge",
    label: "success",
    variant: "success",
    tone: "success",
  },
  "qs.system.badge.warning": {
    id: "qs.system.badge.warning",
    type: "badge",
    label: "warning",
    variant: "warning",
    tone: "warning",
  },
  "qs.system.badge.danger": {
    id: "qs.system.badge.danger",
    type: "badge",
    label: "danger",
    variant: "danger",
    tone: "danger",
  },
  "qs.system.theme.progress": {
    id: "qs.system.theme.progress",
    type: "progress",
    label: "Recipe coverage",
    value: 92,
    variant: "success",
    tone: "success",
  },
  "qs.system.theme.list": {
    id: "qs.system.theme.list",
    type: "list",
    variant: "compact",
    items: [
      { title: "Theme", body: "Default token maps stay inside assets and renderer." },
      { title: "Variants", body: "Catalog names advertise the choices agents can make." },
      { title: "Recipes", body: "Parts style labels, controls, cells, tracks, and fills." },
    ],
  },
  "qs.system.bricks": {
    id: "qs.system.bricks",
    type: "section",
    title: "Component gallery",
    body: "The built-in intrinsic components render through React recipe parts while box, text, media, and input remain the primitive base.",
    variant: "surface",
    children: [
      "qs.system.actions.card",
      "qs.system.data.card",
      "qs.system.form.card",
      "qs.system.feedback.card",
    ],
  },
  "qs.system.actions.card": {
    id: "qs.system.actions.card",
    type: "card",
    title: "Actions and layout",
    body: "Buttons, cards, metrics, badges, progress, dividers, and flow boxes.",
    children: [
      "qs.system.action.buttons",
      "qs.system.action.metric",
      "qs.system.action.progress",
      "qs.system.action.divider",
    ],
  },
  "qs.system.action.buttons": {
    id: "qs.system.action.buttons",
    type: "box",
    style: { direction: "row", gap: "sm", wrap: true },
    children: ["qs.system.button.primary", "qs.system.button.secondary", "qs.system.button.danger"],
  },
  "qs.system.button.primary": {
    id: "qs.system.button.primary",
    type: "button",
    label: "Primary",
    variant: "primary",
    tone: "accent",
    onPress: { kind: "agent", name: "show_primary_action" },
  },
  "qs.system.button.secondary": {
    id: "qs.system.button.secondary",
    type: "button",
    label: "Secondary",
    variant: "secondary",
    onPress: { kind: "agent", name: "show_secondary_action" },
  },
  "qs.system.button.danger": {
    id: "qs.system.button.danger",
    type: "button",
    label: "Danger",
    variant: "danger",
    tone: "danger",
    onPress: { kind: "agent", name: "show_danger_action" },
  },
  "qs.system.action.metric": {
    id: "qs.system.action.metric",
    type: "metric",
    label: "Interactive components",
    value: "12",
    delta: "plus field",
    variant: "success",
    tone: "success",
  },
  "qs.system.action.progress": {
    id: "qs.system.action.progress",
    type: "progress",
    label: "Polish pass",
    value: 76,
    variant: "default",
    tone: "info",
  },
  "qs.system.action.divider": {
    id: "qs.system.action.divider",
    type: "divider",
    label: "Data display",
    variant: "default",
  },
  "qs.system.data.card": {
    id: "qs.system.data.card",
    type: "card",
    title: "Display-only data",
    body: "Tables and charts show bounded data only. They do not fetch, sort, or bind backend state.",
    children: ["qs.system.data.chart", "qs.system.data.table"],
  },
  "qs.system.data.chart": {
    id: "qs.system.data.chart",
    type: "chart",
    title: "Renderer checks",
    kind: "bar",
    variant: "default",
    labels: ["Table", "Chart", "Field", "Composition"],
    series: [{ label: "coverage", values: [3, 4, 3, 5] }],
  },
  "qs.system.data.table": {
    id: "qs.system.data.table",
    type: "table",
    caption: "Catalog variants",
    variant: "default",
    columns: [
      { key: "component", label: "Component" },
      { key: "contract", label: "Variant / role" },
    ],
    rows: [
      { component: "button", contract: "primary, secondary, danger" },
      { component: "table", contract: "display-only rows" },
      { component: "progress", contract: "track and fill" },
      { component: "input", contract: "primitive browser view-state" },
    ],
  },
  "qs.system.form.card": {
    id: "qs.system.form.card",
    type: "card",
    title: "Field controls",
    body: "Field values stay in browser view-state until an action collects them.",
    children: ["qs.system.form.name", "qs.system.form.kind", "qs.system.form.submit"],
  },
  "qs.system.form.name": {
    id: "qs.system.form.name",
    type: "input",
    name: "showcase_name",
    label: "Showcase name",
    placeholder: "Design audit",
    variant: "default",
  },
  "qs.system.form.kind": {
    id: "qs.system.form.kind",
    type: "input",
    name: "showcase_kind",
    input: "select",
    label: "Surface type",
    options: ["Dashboard", "Form", "Catalog", "Workflow"],
    variant: "default",
  },
  "qs.system.form.submit": {
    id: "qs.system.form.submit",
    type: "button",
    label: "Collect field values",
    variant: "secondary",
    onPress: { kind: "agent", name: "inspect_showcase_fields", collect: "qs.system.form.card" },
  },
  "qs.system.feedback.card": {
    id: "qs.system.feedback.card",
    type: "card",
    title: "Feedback patterns",
    body: "Alerts and lists carry product state without overlays, z-index, or absolute positioning.",
    children: ["qs.system.feedback.alert", "qs.system.feedback.list"],
  },
  "qs.system.feedback.alert": {
    id: "qs.system.feedback.alert",
    type: "alert",
    title: "Token-only styling",
    body: "The agent never chooses raw colors, classes, pixels, HTML, or scripts.",
    variant: "success",
    tone: "success",
  },
  "qs.system.feedback.list": {
    id: "qs.system.feedback.list",
    type: "list",
    variant: "default",
    items: [
      { title: "Flow layout", body: "No overlay or absolute-position contracts." },
      { title: "Bounded intent", body: "Variants and tones are the visual knobs." },
      { title: "Fail-safe renderer", body: "Malformed nodes skip instead of throwing." },
    ],
  },
  "qs.system.compositions": {
    id: "qs.system.compositions",
    type: "section",
    title: "Default composition patterns",
    body: "The agent sees composition names, slots, and metadata before it falls back to primitive composition.",
    variant: "surface",
    children: ["qs.system.compositions.list", "qs.system.compositions.table"],
  },
  "qs.system.compositions.list": {
    id: "qs.system.compositions.list",
    type: "list",
    variant: "compact",
    items: [
      { title: "hero", body: "Compact product intro with a call to action." },
      { title: "pricing-section", body: "Three-card plan comparison." },
      { title: "dashboard-summary", body: "KPI metric, status badge, and progress." },
      { title: "settings-panel", body: "Fields plus a collect action." },
      { title: "chart-table-view", body: "Display-only data view." },
    ],
  },
  "qs.system.compositions.table": {
    id: "qs.system.compositions.table",
    type: "table",
    caption: "Composition slots",
    variant: "default",
    columns: [
      { key: "composition", label: "Composition" },
      { key: "slots", label: "Slots" },
    ],
    rows: [
      { composition: "hero", slots: "title, subtitle, cta" },
      { composition: "settings-panel", slots: "title, email, timezone, save" },
      { composition: "support-triage", slots: "issue, details, submit" },
    ],
  },
  "qs.system.catalog": {
    id: "qs.system.catalog",
    type: "section",
    title: "Catalog policy",
    body: "The default order is composition, then component, then primitive fallback. The model chooses intent; assets and renderer own polish.",
    variant: "surface",
    children: ["qs.system.catalog.list"],
  },
  "qs.system.catalog.list": {
    id: "qs.system.catalog.list",
    type: "list",
    variant: "default",
    items: [
      { title: "Theme", body: "default, locked by name" },
      { title: "Component", body: "variant and tone from the catalog only" },
      { title: "Composition", body: "name and slots, never fragment JSON in prompt" },
      { title: "Primitive", body: "box, text, media, and input as fallback base" },
    ],
  },
} satisfies FacetTree["nodes"];
