import type { FacetTree } from "@facet/core";
import { QUICKSTART_NAV_ITEMS } from "./guide-shared.js";

export const QUICKSTART_SYSTEM_NODES = {
  "qs.system.root": {
    id: "qs.system.root",
    type: "box",
    style: { direction: "col", gap: "lg", pad: "xl" },
    children: [
      "qs.nav.system",
      "qs.system.hero",
      "qs.system.theme",
      "qs.system.bricks",
      "qs.system.compositions",
      "qs.system.catalog",
    ],
  },
  "qs.nav.system": {
    id: "qs.nav.system",
    type: "tabs",
    variant: "default",
    items: QUICKSTART_NAV_ITEMS,
  },
  "qs.system.hero": {
    id: "qs.system.hero",
    type: "section",
    eyebrow: "Default assets",
    title: "Design System",
    body: "The agent can introduce the default theme, catalog variants, intrinsic components, fields, and optional composition references through live Facet UI examples.",
    variant: "surface",
    children: ["qs.system.hero.alert"],
  },
  "qs.system.hero.alert": {
    id: "qs.system.hero.alert",
    type: "box",
    style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
    children: ["qs.system.hero.alert.title", "qs.system.hero.alert.body"],
  },
  "qs.system.hero.alert.title": {
    id: "qs.system.hero.alert.title",
    type: "text",
    value: "Renderer QA surface",
    style: { weight: "bold", color: "info" },
  },
  "qs.system.hero.alert.body": {
    id: "qs.system.hero.alert.body",
    type: "text",
    value:
      "This tab doubles as a renderer QA surface for alignment, overflow, native-control, and recipe-part issues.",
    style: { color: "fg" },
  },
  "qs.system.theme": {
    id: "qs.system.theme",
    type: "section",
    title: "Theme recipes",
    body: "Agents choose variants and bounded tones. The renderer resolves token-only recipes into the final UI.",
    variant: "surface",
    children: ["qs.system.theme.badges", "qs.system.theme.progress", "qs.system.theme.list"],
  },
  "qs.system.theme.badges": {
    id: "qs.system.theme.badges",
    type: "box",
    style: { direction: "row", gap: "sm", wrap: true },
    children: [
      "qs.system.badge.neutral",
      "qs.system.badge.success",
      "qs.system.badge.warning",
      "qs.system.badge.danger",
    ],
  },
  "qs.system.badge.neutral": {
    id: "qs.system.badge.neutral",
    type: "box",
    style: { direction: "row", pad: "xs", radius: "full", bg: "surface-2" },
    children: ["qs.system.badge.neutral.label"],
  },
  "qs.system.badge.neutral.label": {
    id: "qs.system.badge.neutral.label",
    type: "text",
    value: "neutral",
    style: { color: "neutral", size: "xs", weight: "semibold" },
  },
  "qs.system.badge.success": {
    id: "qs.system.badge.success",
    type: "box",
    style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
    children: ["qs.system.badge.success.label"],
  },
  "qs.system.badge.success.label": {
    id: "qs.system.badge.success.label",
    type: "text",
    value: "success",
    style: { color: "success", size: "xs", weight: "semibold" },
  },
  "qs.system.badge.warning": {
    id: "qs.system.badge.warning",
    type: "box",
    style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
    children: ["qs.system.badge.warning.label"],
  },
  "qs.system.badge.warning.label": {
    id: "qs.system.badge.warning.label",
    type: "text",
    value: "warning",
    style: { color: "warning", size: "xs", weight: "semibold" },
  },
  "qs.system.badge.danger": {
    id: "qs.system.badge.danger",
    type: "box",
    style: { direction: "row", pad: "xs", radius: "full", bg: "surface", border: true },
    children: ["qs.system.badge.danger.label"],
  },
  "qs.system.badge.danger.label": {
    id: "qs.system.badge.danger.label",
    type: "text",
    value: "danger",
    style: { color: "danger", size: "xs", weight: "semibold" },
  },
  "qs.system.theme.progress": {
    id: "qs.system.theme.progress",
    type: "progress",
    label: "Recipe coverage",
    value: 92,
    variant: "success",
    tone: "success",
  },
  "qs.system.theme.list": {
    id: "qs.system.theme.list",
    type: "list",
    variant: "compact",
    items: [
      { title: "Theme", body: "Default token maps stay inside assets and renderer." },
      { title: "Variants", body: "Catalog names advertise the choices agents can make." },
      { title: "Recipes", body: "Parts style labels, controls, cells, tracks, and fills." },
    ],
  },
  "qs.system.bricks": {
    id: "qs.system.bricks",
    type: "section",
    title: "Component gallery",
    body: "The built-in intrinsic components render through React recipe parts while box, text, media, input, and richtext remain the primitive base.",
    variant: "surface",
    children: [
      "qs.system.actions.card",
      "qs.system.data.card",
      "qs.system.form.card",
      "qs.system.feedback.card",
    ],
  },
  "qs.system.actions.card": {
    id: "qs.system.actions.card",
    type: "card",
    title: "Actions and layout",
    body: "Buttons, cards, metrics, badges, progress, dividers, and flow boxes.",
    children: [
      "qs.system.action.buttons",
      "qs.system.action.metric",
      "qs.system.action.progress",
      "qs.system.action.divider",
    ],
  },
  "qs.system.action.buttons": {
    id: "qs.system.action.buttons",
    type: "box",
    style: { direction: "row", gap: "sm", wrap: true },
    children: ["qs.system.button.primary", "qs.system.button.secondary", "qs.system.button.danger"],
  },
  "qs.system.button.primary": {
    id: "qs.system.button.primary",
    type: "button",
    label: "Primary",
    variant: "primary",
    tone: "accent",
    onPress: { kind: "agent", name: "show_primary_action" },
  },
  "qs.system.button.secondary": {
    id: "qs.system.button.secondary",
    type: "button",
    label: "Secondary",
    variant: "secondary",
    onPress: { kind: "agent", name: "show_secondary_action" },
  },
  "qs.system.button.danger": {
    id: "qs.system.button.danger",
    type: "button",
    label: "Danger",
    variant: "danger",
    tone: "danger",
    onPress: { kind: "agent", name: "show_danger_action" },
  },
  "qs.system.action.metric": {
    id: "qs.system.action.metric",
    type: "metric",
    label: "Interactive components",
    value: "12",
    delta: "plus field",
    variant: "success",
    tone: "success",
  },
  "qs.system.action.progress": {
    id: "qs.system.action.progress",
    type: "progress",
    label: "Polish pass",
    value: 76,
    variant: "default",
    tone: "info",
  },
  "qs.system.action.divider": {
    id: "qs.system.action.divider",
    type: "box",
    style: { border: true, bg: "surface-2", radius: "full" },
    children: [],
  },
  "qs.system.data.card": {
    id: "qs.system.data.card",
    type: "card",
    title: "Display-only data",
    body: "Tables and charts show bounded data only. They do not fetch, sort, or bind backend state.",
    children: ["qs.system.data.chart", "qs.system.data.table"],
  },
  "qs.system.data.chart": {
    id: "qs.system.data.chart",
    type: "chart",
    title: "Renderer checks",
    kind: "bar",
    variant: "default",
    labels: ["Table", "Chart", "Field", "Reference"],
    series: [{ label: "coverage", values: [3, 4, 3, 5] }],
  },
  "qs.system.data.table": {
    id: "qs.system.data.table",
    type: "table",
    caption: "Catalog variants",
    variant: "default",
    columns: [
      { key: "component", label: "Component" },
      { key: "contract", label: "Variant / role" },
    ],
    rows: [
      { component: "button", contract: "primary, secondary, danger" },
      { component: "table", contract: "display-only rows" },
      { component: "progress", contract: "track and fill" },
      { component: "input", contract: "primitive browser view-state" },
    ],
  },
  "qs.system.form.card": {
    id: "qs.system.form.card",
    type: "card",
    title: "Field controls",
    body: "Field values stay in browser view-state until an action collects them.",
    children: ["qs.system.form.name", "qs.system.form.kind", "qs.system.form.submit"],
  },
  "qs.system.form.name": {
    id: "qs.system.form.name",
    type: "input",
    name: "showcase_name",
    label: "Showcase name",
    placeholder: "Design audit",
    variant: "default",
  },
  "qs.system.form.kind": {
    id: "qs.system.form.kind",
    type: "input",
    name: "showcase_kind",
    input: "select",
    label: "Surface type",
    options: ["Dashboard", "Form", "Catalog", "Workflow"],
    variant: "default",
  },
  "qs.system.form.submit": {
    id: "qs.system.form.submit",
    type: "button",
    label: "Collect field values",
    variant: "secondary",
    onPress: { kind: "agent", name: "inspect_showcase_fields", collect: "qs.system.form.card" },
  },
  "qs.system.feedback.card": {
    id: "qs.system.feedback.card",
    type: "card",
    title: "Feedback patterns",
    body: "Alerts and lists carry product state without overlays, z-index, or absolute positioning.",
    children: ["qs.system.feedback.alert", "qs.system.feedback.list"],
  },
  "qs.system.feedback.alert": {
    id: "qs.system.feedback.alert",
    type: "box",
    style: { gap: "sm", pad: "md", bg: "surface", border: true, radius: "md" },
    children: ["qs.system.feedback.alert.title", "qs.system.feedback.alert.body"],
  },
  "qs.system.feedback.alert.title": {
    id: "qs.system.feedback.alert.title",
    type: "text",
    value: "Token-only styling",
    style: { weight: "bold", color: "success" },
  },
  "qs.system.feedback.alert.body": {
    id: "qs.system.feedback.alert.body",
    type: "text",
    value: "The agent never chooses raw colors, classes, pixels, HTML, or scripts.",
    style: { color: "fg" },
  },
  "qs.system.feedback.list": {
    id: "qs.system.feedback.list",
    type: "list",
    variant: "default",
    items: [
      { title: "Flow layout", body: "No overlay or absolute-position contracts." },
      { title: "Bounded intent", body: "Variants and tones are the visual knobs." },
      { title: "Fail-safe renderer", body: "Malformed nodes skip instead of throwing." },
    ],
  },
  "qs.system.compositions": {
    id: "qs.system.compositions",
    type: "section",
    title: "Optional reference datasets",
    body: "For a complex UI, the agent may read one concrete example by name, then copy or adapt its ordinary native nodes. Simple UI can be authored directly without a lookup.",
    variant: "surface",
    children: ["qs.system.compositions.list", "qs.system.compositions.table"],
  },
  "qs.system.compositions.list": {
    id: "qs.system.compositions.list",
    type: "list",
    variant: "compact",
    items: [
      { title: "Optional read", body: "Inspect one advertised example only when it helps." },
      { title: "Read-only", body: "Looking up an example never edits the visitor stage." },
      {
        title: "Native authoring",
        body: "Write the final page separately with ordinary components and primitives.",
      },
    ],
  },
  "qs.system.compositions.table": {
    id: "qs.system.compositions.table",
    type: "table",
    caption: "Reference examples",
    variant: "default",
    columns: [
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
    ],
    rows: [
      {
        name: "hero",
        description: "A compact product hero with a title, subtitle, and CTA.",
      },
      {
        name: "dashboard-summary",
        description: "A KPI summary section with stats and status.",
      },
      {
        name: "settings-panel",
        description: "A settings card with two editable fields and a save action.",
      },
    ],
  },
  "qs.system.catalog": {
    id: "qs.system.catalog",
    type: "section",
    title: "Catalog policy",
    body: "The default authoring order is component, then primitive fallback. A separate composition allow-list controls which optional references are advertised.",
    variant: "surface",
    children: ["qs.system.catalog.list"],
  },
  "qs.system.catalog.list": {
    id: "qs.system.catalog.list",
    type: "list",
    variant: "default",
    items: [
      { title: "Theme", body: "default, locked by name" },
      { title: "Component", body: "variant and tone from the catalog only" },
      { title: "Reference", body: "name and short description; full example only on demand" },
      { title: "Primitive", body: "box, text, media, input, and richtext as fallback base" },
    ],
  },
} satisfies FacetTree["nodes"];
