/**
 * The canonical description of the Facet stage vocabulary — primitive bricks,
 * components, catalog policy, and style tokens — for prompting an LLM. This is
 * the SINGLE source: every agent-driving path (the CLI generator, the bridge
 * spawn prompt, the persistent tools) embeds it and wraps it with its own action
 * instructions, so the vocabulary never drifts from `nodes.ts` / `tokens.ts`.
 */
export const STAGE_SPEC = `A Facet stage tree is { "root": "root", "nodes": { "<id>": <node> }, "screens"?: { "<name>": <root node id> }, "entry"?: "<name>", "theme"?: "<theme name>", "data"?: { "<datasetName>": [ <row objects> ] } } — a flat map where every referenced child id exists in nodes. "root" and each screen target must be a screen root container: box or form. "screens" are named roots into the same flat nodes map (screens may share nodes); "entry" is the screen shown first. No screens ⇒ "root" renders. Set top-level "theme" only to a theme name you have been given (a THEMES list, if any) — you never write CSS values, styles stay tokens; an unknown or missing name falls back to the default look.

Agent-facing authoring order: component -> primitive fallback. Primitive bricks are the universal base and fallback: box, text, media, input, richtext. Components are locked Facet/platform-managed node shapes for common UI; the catalog tells you which components, variants, and themes are available for this session, and may separately list compositions as optional reference datasets by name and short description. Intrinsic components are locked: button, tabs, nav, table, chart, metric, keyValue, progress, list, form, filterBar, loading. "stat" remains legacy compatibility; prefer metric for new KPI and summary values. Badges and alerts are NOT node types; cards, content sections, and empty states are not node types either — author their appearance with native boxes, text, buttons, and components. When useful, a named reference dataset can provide guidance for those patterns. Author the result as ordinary native nodes. To separate content, use a plain box (e.g. a thin bordered/padded box) rather than a node type.

Node types (the ONLY allowed types):
- box:   { "id", "type":"box", "children":[ids], "variant"?:name, "style"?:BoxStyle, "hidden"?:bool, "backdrop"?:<mediaNodeId>, "overlay"?:{ "kind":("modal"|"drawer") }, "onPress"?:Action, "onHold"?:Action, "activeVariant"?:name, "activeStyle"?:BoxStyle, "active"?:ViewPredicate } — primitive container and fallback layout. Flow-only layout (no absolute positioning). "onHold" is a secondary long-press gesture (same Action union as onPress) — never make hold the only path to critical content. "backdrop" references a media node id to paint as a bounded BACKGROUND layer behind this box's flow children (renderer-owned two-layer, no overlap/z-index; the id MUST be a media node); flow children stay in normal flow. "overlay" floats this box ABOVE flow as a "modal" (renderer-centered over a scrim) or "drawer" (renderer-placed at the end edge over a scrim) — you give ONLY "kind"; the renderer owns placement, scrim, z, and focus, never coordinates/size/z/position. Open and close it with the EXISTING "toggle" action on this box's id (start it "hidden":true; a button onPress toggle opens it; Esc, the scrim, or a close button close it) — no agent turn.
  Action: {"kind":"agent","name":string,"collect"?:<containerId>} | {"kind":"navigate","to":<screen>} | {"kind":"toggle","target":<nodeId>}. navigate/toggle run instantly in the visitor's browser with no agent turn — pre-draw your screens and hidden panels so they work while you are idle; use "kind":"agent" (or bare {"name"}) for anything open-ended. "collect": pressing an agent action snapshots the values of visible fields on the current screen within that container subtree into the event's "fields", keyed by each field's "name" — text/select/radio values are strings, checked checkbox/switch values are boolean true, unchecked checkbox/switch controls are omitted. Give fields stable names, and keep a form and its submit button together and visible on one screen (hidden fields, fields on other screens, and password fields are never captured).
- text:  { "id", "type":"text", "value":string, "variant"?:name, "style"?:TextStyle, "from"?:datasetName, "column"?:name, "row"?:number, "activeVariant"?:name, "activeStyle"?:TextStyle, "active"?:ViewPredicate } — "from"+"column"+optional "row" (default 0) read ONE dataset cell as the value ("from" wins over inline "value"); see Data binding and Active look below.
- media: { "id", "type":"media", "kind":("image"|"video"), "src":url, "variant"?:name, "alt"?:string, "poster"?:url, "controls"?:bool, "style"?:MediaStyle } — use kind:"image" with https://picsum.photos/seed/<word>/600/400 for sample images; kind:"video" may use poster/controls.
- input: { "id", "type":"input", "name":string, "variant"?:name, "label"?, "placeholder"?, "input"?:("text"|"number"|"email"|"password"|"search"|"checkbox"|"radio"|"select"|"switch"), "options"?:[strings], "style"?:{"width"?} } — the primitive input control; select/radio use options; checkbox/switch are boolean controls. For a search box with a submit, compose an input (input:"search") with a button whose onPress "collect" points at the container holding the input.
- richtext: { "id", "type":"richtext", "blocks":[ { "type":("paragraph"|"heading"|"listItem"|"quote"), "level"?:1..3, "depth"?:0..5, "runs":[ { "text":string, "marks"?:[ {"kind":("bold"|"italic"|"underline"|"strike"|"code")} | {"kind":"link","target":Action|{"href":url}} ] } ] } ], "variant"?:name, "style"?:TextStyle } — a flowing block of prose carrying MIXED inline formatting the single-string "text" node cannot express. A primitive LEAF brick: it holds its own "blocks"/"runs" (no child ids, no "from" binding) and its block typography is the same TextStyle token family as text. "blocks" stack vertically; a block's "runs" flow inline and wrap within it. "marks" are CLOSED semantic NAMES (bold, italic, underline, strike, code, link) — never raw HTML, markdown, or CSS; an unknown mark is dropped and the run text kept. "heading" carries "level" (rank 1–3, clamped); "listItem" carries "depth" (renderer-owned FLOW indent 0–5, clamped) — no author pixels or positioning. A "link" mark's "target" is either an INTERNAL Action (navigate/agent/toggle — the same Action union as onPress) OR a gated EXTERNAL {"href":url} (only http(s)/protocol-relative/local paths; javascript:/data: and other schemes are dropped and the run rendered inert) — a link is navigated, never fetched.
- button: { "id", "type":"button", "label":string, "variant"?:name, "tone"?:tone, "disabled"?:bool, "onPress"?:Action, "onHold"?:Action } — use for direct actions instead of hand-rolled pressable boxes.
- tabs: { "id", "type":"tabs", "items":[{"label":string,"to":screen}], "variant"?:name } — navigation wrapper over existing local navigate semantics; it does not mutate stage content.
- nav: { "id", "type":"nav", "items":[{"label":string,"to":screen}], "variant"?:name } — app or section navigation over existing local navigate semantics.
- table: { "id", "type":"table", "columns":[{"key":name,"label":string,"align"?:"start"|"center"|"end","sortable"?:boolean}], "rows":[objects], "from"?:datasetName, "caption"?, "variant"?:name } — display-only capped tabular data. Mark a column "sortable":true to let the visitor click its header to reorder the rows locally (ascending -> descending -> unsorted) with no agent turn; the renderer owns the closed comparator, you author no sort logic, and the current sort rides the visitor's next event so you can see how they sorted.
- chart: { "id", "type":"chart", "kind":("bar"|"line"|"donut"), "series":[{"label":string,"values":[numbers]}], "from"?:datasetName, "labels"?:[strings], "title"?, "variant"?:name } — display-only capped chart data.
- metric: { "id", "type":"metric", "label":string, "value":string, "from"?:datasetName, "column"?:name, "row"?:number, "delta"?, "tone"?:tone, "variant"?:name }
- keyValue: { "id", "type":"keyValue", "items":[{"label":string,"value":string,"tone"?:tone}], "from"?:datasetName, "variant"?:name }
- progress: { "id", "type":"progress", "value":0..100, "label"?, "tone"?:tone, "variant"?:name }
- list: { "id", "type":"list", "items":[string|{"title":string,"body"?}], "from"?:datasetName, "variant"?:name }
- form: { "id", "type":"form", "title"?, "body"?, "submitLabel"?, "variant"?:name, "onSubmit"?:Action, "children":[ids] } — grouped visitor input; submit uses the same agent action and field collection semantics.
- filterBar: { "id", "type":"filterBar", "filters":[{"name":string,"label":string,"input"?, "options"?, "value"?}], "variant"?:name, "onChange"?:Action } — compact filtering controls UI only.
- loading: { "id", "type":"loading", "label"?, "variant"?:name }
- stat: { "id", "type":"stat", "label":string, "value":string, "from"?:datasetName, "column"?:name, "row"?:number, "delta"?, "tone"?:tone, "variant"?:name } — legacy metric compatibility; prefer metric.

Data binding (author once, bind many): put rows the page reuses in the top-level "data" warehouse — a map of dataset NAME to an array of flat row records (each value a string, number, or boolean; no nested objects). A table/chart/list/keyValue/metric/stat/text may set "from":datasetName to render FROM that dataset instead of its own inline array/value; "from" wins over inline. Projection is fixed per type: a table shows the rows and its columns[].key pick the cells; a chart draws one series per NUMERIC column; a list takes the first two STRING columns (title, then body) and keyValue the first two columns in order; a metric/stat/text reads ONE cell via "column" plus optional "row" (default 0). Update a dataset (or one cell) once and every bound view updates together. "from", "column", and dataset names are plain NAMES, never a URL/endpoint/query/expression/resolver — there is no fetch or computed column; a "from" naming a missing dataset simply renders empty until you author the data.

Active look (highlight the current view): any box or text may add "activeVariant" (a recipe name, preferred) and/or "activeStyle" (extra style tokens, sanitized by the SAME token rules as "style"), applied ONLY while its "active" predicate holds. "active" is a CLOSED view-state predicate — one of { "screen":name } (active while the visitor is on that screen) or { "toggled":nodeId } (active while that node id is locally toggled-shown) — never an expression or resolver. The renderer evaluates it READ-ONLY against the current view with no agent turn and no event, folding the active recipe/tokens over the base look; an unknown/dangling predicate keeps the default look. Prefer "activeVariant" over raw "activeStyle" so the active channel stays token-only. Use it to light up the current tab/nav item or a toggled panel with zero round-trips.

Containers are box and form. Tables, charts, and filterBar are display/control-only: no client-side fetch, query expression, endpoint, resolver, or browser business logic you author. The only local reordering is a table's built-in "sortable" columns — a closed renderer-owned comparator you opt into with a flag, never a sort engine or comparator you write. Backend work stays with the agent through actions/tools and patching new data into the stage (including the "data" warehouse).

Composition reference boundary: compositions are concrete native node examples, made only of validated nodes and loaded as assets for optional design guidance. If a composition list is available, read a relevant reference by name only when useful, then author its ideas as ordinary native nodes with the normal stage actions. A reference read does not mutate the stage, insert nodes, or grant new node kinds, tokens, layout powers, data access, or browser behavior. Treat the example as guidance rather than copying it blindly; every authored node still passes the same closed native validation.

Renderer layout contract: the parent controls placement and each component owns its internal layout within that placement. Layout is flow-only, boxes and component roots are bounded to their parent, bounded overflow is the default for long content, long content wraps or clips within renderer-owned bounds, and horizontal overflow is allowed only inside an explicit renderer-owned scroll region.

Style values MUST be tokens (never pixels or hex):
- BoxStyle: direction(row|col), gap/pad(none|xs|sm|md|lg|xl|2xl), align(start|center|end|stretch), justify(start|center|end|between|around), wrap(bool), bg(color), radius(none|sm|md|lg|full), border(bool), grow(bool), width(auto|full), minHeight(auto|half|screen), maxWidth(none|prose|narrow|wide), sticky(bool), gradient(none|accent|dusk|dawn), backdropScrim(none|light|dark), scheme(light|dark), appear(none|fade|slide), scroll(x|y), columns(2|3|4), shadow(none|sm|md|lg) — appear animates the node's entry and replays on each re-show (toggle, navigation, re-add); the renderer owns the timing and honors reduced motion. scroll:"y" makes the box a bounded, internally-scrolling region for long lists (the renderer owns the max height); scroll:"x" makes a bounded horizontal region; columns creates a flow-safe grid and ignores direction/wrap.
- TextStyle: family(sans|serif|mono), size(xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl), weight(regular|medium|semibold|bold), color(color), align(start|center|end), tracking(tight|normal|wide), leading(tight|normal|relaxed), highlight(none|accent|band)
- MediaStyle: radius(none|sm|md|lg|full), width(auto|full), ratio(square|wide|tall)
- color tokens: fg, fg-muted, bg, surface, surface-2, accent, accent-fg, border, neutral, info, success, warning, danger, chart-1, chart-2, chart-3, chart-4, chart-5, chart-6

Landing/hero layouts: the landing-grade tokens compose full-bleed marketing sections from the same closed vocabulary. A full-height hero is a box with "backdrop" (a media node id) + minHeight:"screen" holding a large-size headline (add a "highlight" run) and a call-to-action button; use sticky for a sticky nav bar, scheme:"dark" for dark bands, gradient for gradient backgrounds, and backdropScrim to keep copy legible over a backdrop image. Every one is a CLOSED token NAME the theme resolves to the concrete look — never raw CSS, pixels, or hex.

Example (2 screens + a hidden menu panel):
{ "root":"root", "screens":{"home":"root","about":"about"}, "entry":"home", "nodes":{
  "root":{"id":"root","type":"box","children":["menu-btn","menu","home-text"]},
  "menu-btn":{"id":"menu-btn","type":"box","children":["menu-label"],"onPress":{"kind":"toggle","target":"menu"}},
  "menu-label":{"id":"menu-label","type":"text","value":"☰ Menu"},
  "menu":{"id":"menu","type":"box","hidden":true,"children":["to-about"]},
  "to-about":{"id":"to-about","type":"box","children":["about-label"],"onPress":{"kind":"navigate","to":"about"}},
  "about-label":{"id":"about-label","type":"text","value":"About"},
  "home-text":{"id":"home-text","type":"text","value":"Welcome"},
  "about":{"id":"about","type":"box","children":["about-text"]},
  "about-text":{"id":"about-text","type":"text","value":"About us"} } }`;
